use std::fmt::Debug;
use std::hash::Hash;

/// An entity is a thing that exists in an ontology — an object in the category.
///
/// Entities must be finite and enumerable. Every entity can list all possible
/// values of its type, enabling exhaustive validation of ontology properties.
///
/// Can be derived for enums with unit variants:
/// ```
/// use pr4xis::category::Entity;
///
/// #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Entity)]
/// enum Color { Red, Green, Blue }
///
/// assert_eq!(Color::variants().len(), 3);
/// ```
pub trait Entity: Sized + Clone + Eq + Hash + Debug + 'static {
    /// All possible entities of this type.
    fn variants() -> Vec<Self>;

    /// The name of this entity variant — generated by the derive macro.
    fn name(&self) -> &'static str {
        ""
    }
}

/// Metadata about entity variants — generated by the derive macro
/// from `/// doc comments`. Separate from the Entity trait because
/// descriptions are metadata ABOUT the entity, not behavior OF it.
///
/// The derive macro generates a const `<TypeName>_META: &[EntityMeta]`
/// for each entity enum. The vocabulary system reads it.
#[derive(Debug, Clone)]
pub struct EntityMeta {
    pub name: &'static str,
    pub description: &'static str,
}

#[cfg(test)]
mod tests {
    use super::*;
    use pr4xis_derive::Entity;

    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Entity)]
    enum TestEntity {
        A,
        B,
        C,
    }

    #[test]
    fn derive_entity_produces_all_variants() {
        let v = TestEntity::variants();
        assert_eq!(v.len(), 3);
        assert_eq!(v[0], TestEntity::A);
        assert_eq!(v[1], TestEntity::B);
        assert_eq!(v[2], TestEntity::C);
    }

    #[test]
    fn derive_entity_single_variant() {
        #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Entity)]
        enum Single {
            Only,
        }
        assert_eq!(Single::variants(), vec![Single::Only]);
    }
}
