//! Regeneration science ontology based on Dr. Michael Levin's research.
//!
//! Models the biology of regeneration — how organisms restore lost or damaged
//! structures — using formal ontological categories, taxonomies, causal graphs,
//! qualities, and axioms.
//!
//! Key scientific facts encoded:
//! - Epimorphic regeneration (salamander limb) requires blastema + nerve supply
//! - Morphallactic regeneration (planarian) remodels without growth
//! - Bioelectric signals specify pattern during regeneration (Levin's core insight)
//! - Gap junction communication enables collective decision-making in tissues
//! - Planarian head/tail polarity is bistable and can be stochastically edited
//!   (Levin 2015, PMID:26610482)
//! - Epithelial restitution is purely cell-migration-based, no bioelectric signal
//!
//! Key references:
//! - Levin 2012: Molecular bioelectricity in developmental biology
//! - Levin 2015: planarian anterior/posterior polarity editing
//! - Kumar & Brockes 2012: nerve dependence in amphibian regeneration
//! - Oviedo et al. 2010: gap junctions in planarian regeneration

use pr4xis::category::Entity;
use pr4xis::define_ontology;
use pr4xis::ontology::reasoning::causation;
use pr4xis::ontology::reasoning::taxonomy;
use pr4xis::ontology::{Axiom, Ontology, Quality};

// ---------------------------------------------------------------------------
// Regeneration Entity
// ---------------------------------------------------------------------------

/// Every entity in the regeneration ontology.
///
/// Covers regeneration types, pattern concepts, body axes, and structures.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Entity)]
pub enum RegenerationEntity {
    // Regeneration types
    /// Regrowth via blastema formation (e.g. salamander limb).
    Epimorphic,
    /// Remodeling of existing tissue without growth (e.g. planarian).
    Morphallactic,
    /// Organ regrowth by cell proliferation (e.g. liver).
    Compensatory,
    /// Regeneration driven by resident stem cells.
    StemCellMediated,
    /// Rapid wound healing by cell migration (e.g. gut epithelium).
    EpithelialRestitution,

    // Pattern concepts
    /// The target shape the tissue "knows" to regenerate toward.
    TargetMorphology,
    /// Directional information encoded in tissue (head vs tail, etc.).
    AnatomicalPolarity,
    /// Head-to-tail axis.
    AnteriorPosteriorAxis,
    /// Back-to-belly axis.
    DorsalVentralAxis,
    /// Left-right asymmetry axis.
    LeftRightAxis,
    /// Stored morphogenetic information that persists across regeneration cycles.
    PatternMemory,
    /// Two stable attractor states — e.g. planarian head/tail polarity can be
    /// stochastically edited between two stable configurations (Levin 2015).
    Bistability,

    // Structures
    /// Proliferative cell mass at wound site (epimorphic regeneration).
    Blastema,
    /// Epithelial sheet covering wound, signals to underlying tissue.
    WoundEpithelium,
    /// Nerve fibers required for blastema maintenance and growth.
    NerveSupply,

    // Abstract categories
    /// Abstract: a type of regeneration.
    RegenerationType,
    /// Abstract: a body axis.
    BodyAxis,
    /// Abstract: a pattern-related concept.
    PatternConcept,
    /// Abstract: a physical structure involved in regeneration.
    Structure,
}

// ---------------------------------------------------------------------------
// Taxonomy (is-a)
// ---------------------------------------------------------------------------

// Subsumption hierarchy for regeneration entities.
//
// - Regeneration types -> RegenerationType
// - Body axes -> BodyAxis -> PatternConcept
// - Pattern concepts -> PatternConcept
// - Structures -> Structure
// (Taxonomy, Causation, Opposition generated by define_ontology! below)

// ---------------------------------------------------------------------------
// Regeneration Event (causal graph)
// ---------------------------------------------------------------------------

/// Events in the regenerative causal chain.
///
/// Models the temporal sequence from injury through restoration, including
/// bioelectric and gap-junction-mediated signaling pathways.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Entity)]
pub enum RegenerationEvent {
    /// Tissue damage initiating the regeneration cascade.
    Injury,
    /// Wound closure by epithelial migration.
    WoundClosure,
    /// Formation of the blastema (proliferative cell mass).
    BlastemaFormation,
    /// Specification of the regeneration pattern (what to build).
    PatternSpecification,
    /// Terminal differentiation of cells into target tissue types.
    Differentiation,
    /// Full restoration of the original morphology.
    MorphologicalRestoration,
    /// Bioelectric signal (Vmem changes) encoding pattern information.
    BioelectricSignal,
    /// Determination of tissue polarity (head vs tail, etc.).
    PolarityDetermination,
    /// Intercellular communication via gap junctions.
    GapJunctionCommunication,
    /// Collective tissue-level decision about target morphology.
    CollectiveDecision,
    /// Nerve-derived signals maintaining blastema growth.
    NerveSignaling,
}

// ---------------------------------------------------------------------------
// Causal graph
// ---------------------------------------------------------------------------

// Causal relationships in regeneration.
//
// Encodes the directed acyclic graph of causal dependencies:
// - Main chain: Injury -> WoundClosure -> BlastemaFormation -> PatternSpecification
//   -> Differentiation -> MorphologicalRestoration
// - Bioelectric pathway: BioelectricSignal -> PolarityDetermination -> PatternSpecification
// - Gap junction pathway: GapJunctionCommunication -> CollectiveDecision -> PatternSpecification
// - Nerve pathway: NerveSignaling -> BlastemaFormation
define_ontology! {
    /// Regeneration ontology: types, patterns, causal chains.
    pub RegenerationOntologyMeta for RegenerationCategory {
        entity: RegenerationEntity,
        relation: RegenerationRelation,
        being: Process,
        source: "Levin (2012); Kumar & Brockes (2012)",

        taxonomy: RegenerationTaxonomy [
            (Epimorphic, RegenerationType),
            (Morphallactic, RegenerationType),
            (Compensatory, RegenerationType),
            (StemCellMediated, RegenerationType),
            (EpithelialRestitution, RegenerationType),
            (AnteriorPosteriorAxis, BodyAxis),
            (DorsalVentralAxis, BodyAxis),
            (LeftRightAxis, BodyAxis),
            (BodyAxis, PatternConcept),
            (TargetMorphology, PatternConcept),
            (AnatomicalPolarity, PatternConcept),
            (PatternMemory, PatternConcept),
            (Bistability, PatternConcept),
            (Blastema, Structure),
            (WoundEpithelium, Structure),
            (NerveSupply, Structure),
        ],

        causation: RegenerationCauses for RegenerationEvent [
            (Injury, WoundClosure),
            (WoundClosure, BlastemaFormation),
            (BlastemaFormation, PatternSpecification),
            (PatternSpecification, Differentiation),
            (Differentiation, MorphologicalRestoration),
            (BioelectricSignal, PolarityDetermination),
            (PolarityDetermination, PatternSpecification),
            (GapJunctionCommunication, CollectiveDecision),
            (CollectiveDecision, PatternSpecification),
            (NerveSignaling, BlastemaFormation),
        ],

        opposition: RegenerationOpposition [
            (Epimorphic, EpithelialRestitution),
            (Blastema, WoundEpithelium),
            (TargetMorphology, Bistability),
        ],
    }
}

// ---------------------------------------------------------------------------
// Qualities
// ---------------------------------------------------------------------------

/// Quality: does this regeneration type require blastema formation?
///
/// Epimorphic regeneration forms a blastema; morphallactic, compensatory,
/// stem-cell-mediated, and epithelial restitution do not.
#[derive(Debug, Clone)]
pub struct RequiresBlastema;

impl Quality for RequiresBlastema {
    type Individual = RegenerationEntity;
    type Value = bool;

    fn get(&self, individual: &RegenerationEntity) -> Option<bool> {
        use RegenerationEntity::*;
        match individual {
            Epimorphic => Some(true),
            Morphallactic | Compensatory | StemCellMediated | EpithelialRestitution => Some(false),
            _ => None,
        }
    }
}

/// Quality: does this regeneration type require nerve supply?
///
/// Epimorphic regeneration in most organisms depends on nerve-derived factors
/// (Kumar & Brockes 2012). Other types do not.
#[derive(Debug, Clone)]
pub struct RequiresNerveSupply;

impl Quality for RequiresNerveSupply {
    type Individual = RegenerationEntity;
    type Value = bool;

    fn get(&self, individual: &RegenerationEntity) -> Option<bool> {
        use RegenerationEntity::*;
        match individual {
            Epimorphic => Some(true),
            Morphallactic | Compensatory | StemCellMediated | EpithelialRestitution => Some(false),
            _ => None,
        }
    }
}

/// Quality: is the polarity/pattern reversible by bioelectric manipulation?
///
/// Planarian head/tail polarity can be reversed by modulating Vmem via
/// gap junction blockers (Levin 2015, PMID:26610482). This demonstrates
/// that anatomical pattern is stored as a bistable bioelectric state.
#[derive(Debug, Clone)]
pub struct IsReversible;

impl Quality for IsReversible {
    type Individual = RegenerationEntity;
    type Value = bool;

    fn get(&self, individual: &RegenerationEntity) -> Option<bool> {
        use RegenerationEntity::*;
        match individual {
            AnatomicalPolarity | Bistability => Some(true),
            TargetMorphology | PatternMemory => Some(false),
            AnteriorPosteriorAxis | DorsalVentralAxis | LeftRightAxis => Some(true),
            _ => None,
        }
    }
}

/// Characteristic timescale for different regeneration types.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum RegenerationTimescale {
    /// Hours (e.g. epithelial restitution in gut).
    Hours,
    /// Days (e.g. planarian head regeneration ~7 days).
    Days,
    /// Weeks (e.g. salamander limb regeneration ~4-8 weeks).
    Weeks,
    /// Months (e.g. liver compensatory regrowth ~2-3 months).
    Months,
}

/// Quality: how fast does this type of regeneration occur?
#[derive(Debug, Clone)]
pub struct RegenerationSpeed;

impl Quality for RegenerationSpeed {
    type Individual = RegenerationEntity;
    type Value = RegenerationTimescale;

    fn get(&self, individual: &RegenerationEntity) -> Option<RegenerationTimescale> {
        use RegenerationEntity::*;
        use RegenerationTimescale::*;
        match individual {
            EpithelialRestitution => Some(Hours),
            Morphallactic => Some(Days),
            Epimorphic | StemCellMediated => Some(Weeks),
            Compensatory => Some(Months),
            _ => None,
        }
    }
}

/// Quality: does this regeneration type require bioelectric signaling?
///
/// Most regeneration types depend on bioelectric signals for pattern
/// specification (Levin's core insight). Epithelial restitution is the
/// exception — it is purely cell-migration-based wound healing.
#[derive(Debug, Clone)]
pub struct RequiresBioelectricSignal;

impl Quality for RequiresBioelectricSignal {
    type Individual = RegenerationEntity;
    type Value = bool;

    fn get(&self, individual: &RegenerationEntity) -> Option<bool> {
        use RegenerationEntity::*;
        match individual {
            Epimorphic | Morphallactic | Compensatory | StemCellMediated => Some(true),
            EpithelialRestitution => Some(false),
            _ => None,
        }
    }
}

// ---------------------------------------------------------------------------
// Model organism quality
// ---------------------------------------------------------------------------

/// Model organism in which this regeneration type is best studied.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum ModelOrganism {
    Salamander, // axolotl, newt
    Planarian,  // flatworm
    Zebrafish,
    Mouse,
    Human,
}

#[derive(Debug, Clone)]
pub struct PrimaryModelOrganism;

impl Quality for PrimaryModelOrganism {
    type Individual = RegenerationEntity;
    type Value = ModelOrganism;

    fn get(&self, entity: &RegenerationEntity) -> Option<ModelOrganism> {
        use RegenerationEntity::*;
        match entity {
            Epimorphic => Some(ModelOrganism::Salamander),
            Morphallactic => Some(ModelOrganism::Planarian),
            Compensatory => Some(ModelOrganism::Zebrafish), // liver, heart
            StemCellMediated => Some(ModelOrganism::Mouse),
            EpithelialRestitution => Some(ModelOrganism::Human),
            _ => None,
        }
    }
}

// ---------------------------------------------------------------------------
// Opposition (semantic contrasts)
// ---------------------------------------------------------------------------

// Opposition pairs in the regeneration domain.
//
// - Epimorphic <-> EpithelialRestitution: most complex vs simplest regeneration
// - Blastema <-> WoundEpithelium: proliferative structure vs protective barrier
// - TargetMorphology <-> Bistability: single attractor vs multiple stable states

// ---------------------------------------------------------------------------
// Axioms
// ---------------------------------------------------------------------------

/// Axiom: Injury transitively causes MorphologicalRestoration.
///
/// The complete regeneration cascade: Injury -> ... -> MorphologicalRestoration.
pub struct InjuryCausesRestoration;

impl Axiom for InjuryCausesRestoration {
    fn description(&self) -> &str {
        "injury transitively causes morphological restoration"
    }

    fn holds(&self) -> bool {
        use RegenerationEvent::*;
        let effects = causation::effects_of::<RegenerationCauses>(&Injury);
        effects.contains(&MorphologicalRestoration)
    }
}
pr4xis::register_axiom!(InjuryCausesRestoration);

/// Axiom: BioelectricSignal causes PatternSpecification (Levin's core insight).
///
/// Bioelectric signals (Vmem patterns) encode and specify the target morphology
/// during regeneration. This is the central thesis of Levin's bioelectric code.
pub struct BioelectricCausesPattern;

impl Axiom for BioelectricCausesPattern {
    fn description(&self) -> &str {
        "bioelectric signal causes pattern specification (Levin's core insight)"
    }

    fn holds(&self) -> bool {
        use RegenerationEvent::*;
        let effects = causation::effects_of::<RegenerationCauses>(&BioelectricSignal);
        effects.contains(&PatternSpecification)
    }
}
pr4xis::register_axiom!(BioelectricCausesPattern);

/// Axiom: GapJunctionCommunication causes CollectiveDecision.
///
/// Gap junctions enable tissue-level bioelectric signal propagation,
/// allowing cells to collectively compute the target morphology
/// (Oviedo et al. 2010).
pub struct GapJunctionCausesCollectiveDecision;

impl Axiom for GapJunctionCausesCollectiveDecision {
    fn description(&self) -> &str {
        "gap junction communication causes collective decision"
    }

    fn holds(&self) -> bool {
        use RegenerationEvent::*;
        let effects = causation::effects_of::<RegenerationCauses>(&GapJunctionCommunication);
        effects.contains(&CollectiveDecision)
    }
}
pr4xis::register_axiom!(GapJunctionCausesCollectiveDecision);

/// Axiom: PatternMemory is a PatternConcept, NOT a RegenerationType.
///
/// Pattern memory describes stored morphogenetic information — it is a
/// concept about patterning, not a type of regeneration.
pub struct PatternMemoryIsNotRegenerationType;

impl Axiom for PatternMemoryIsNotRegenerationType {
    fn description(&self) -> &str {
        "PatternMemory is a PatternConcept, not a RegenerationType"
    }

    fn holds(&self) -> bool {
        use RegenerationEntity::*;
        taxonomy::is_a::<RegenerationTaxonomy>(&PatternMemory, &PatternConcept)
            && !taxonomy::is_a::<RegenerationTaxonomy>(&PatternMemory, &RegenerationType)
    }
}
pr4xis::register_axiom!(PatternMemoryIsNotRegenerationType);

/// Axiom: Bistability exists — planarian polarity is a bistable bioelectric state.
///
/// Levin (2015, PMID:26610482) showed that planarian head/tail identity is
/// stored as a bistable Vmem pattern that can be stochastically switched
/// between two stable attractors via gap junction modulation.
pub struct BistabilityIsPatterning;

impl Axiom for BistabilityIsPatterning {
    fn description(&self) -> &str {
        "bistability is a pattern concept and is reversible (Levin 2015)"
    }

    fn holds(&self) -> bool {
        use RegenerationEntity::*;
        taxonomy::is_a::<RegenerationTaxonomy>(&Bistability, &PatternConcept)
            && IsReversible.get(&Bistability) == Some(true)
    }
}
pr4xis::register_axiom!(BistabilityIsPatterning);

/// Axiom: Epimorphic regeneration requires BOTH blastema AND nerve supply.
///
/// Salamander limb regeneration depends on blastema formation and continuous
/// nerve-derived trophic factors (Kumar & Brockes 2012).
pub struct EpimorphicRequiresBlastemaAndNerve;

impl Axiom for EpimorphicRequiresBlastemaAndNerve {
    fn description(&self) -> &str {
        "epimorphic regeneration requires both blastema and nerve supply"
    }

    fn holds(&self) -> bool {
        use RegenerationEntity::*;
        RequiresBlastema.get(&Epimorphic) == Some(true)
            && RequiresNerveSupply.get(&Epimorphic) == Some(true)
    }
}
pr4xis::register_axiom!(EpimorphicRequiresBlastemaAndNerve);

/// Axiom: EpithelialRestitution does NOT require bioelectric signaling.
///
/// Epithelial restitution is a rapid, cell-migration-based wound healing
/// process that does not depend on bioelectric pattern specification.
pub struct EpithelialRestitutionNoBioelectric;

impl Axiom for EpithelialRestitutionNoBioelectric {
    fn description(&self) -> &str {
        "epithelial restitution does not require bioelectric signal"
    }

    fn holds(&self) -> bool {
        use RegenerationEntity::*;
        RequiresBioelectricSignal.get(&EpithelialRestitution) == Some(false)
    }
}
pr4xis::register_axiom!(EpithelialRestitutionNoBioelectric);

/// Axiom: all three body axes (AP, DV, LR) are represented as BodyAxis.
pub struct AllBodyAxesRepresented;

impl Axiom for AllBodyAxesRepresented {
    fn description(&self) -> &str {
        "all three body axes (AP, DV, LR) are represented"
    }

    fn holds(&self) -> bool {
        use RegenerationEntity::*;
        let descendants = taxonomy::descendants::<RegenerationTaxonomy>(&BodyAxis);
        descendants.contains(&AnteriorPosteriorAxis)
            && descendants.contains(&DorsalVentralAxis)
            && descendants.contains(&LeftRightAxis)
            && descendants.len() == 3
    }
}
pr4xis::register_axiom!(AllBodyAxesRepresented);

// ---------------------------------------------------------------------------
// Ontology
// ---------------------------------------------------------------------------

/// Top-level ontology tying together the regeneration category, qualities, and axioms.
pub struct RegenerationOntology;

impl Ontology for RegenerationOntology {
    type Cat = RegenerationCategory;
    type Qual = RequiresBioelectricSignal;

    fn structural_axioms() -> Vec<Box<dyn Axiom>> {
        RegenerationOntologyMeta::generated_structural_axioms()
    }

    fn domain_axioms() -> Vec<Box<dyn Axiom>> {
        vec![
            Box::new(InjuryCausesRestoration),
            Box::new(BioelectricCausesPattern),
            Box::new(GapJunctionCausesCollectiveDecision),
            Box::new(PatternMemoryIsNotRegenerationType),
            Box::new(BistabilityIsPatterning),
            Box::new(EpimorphicRequiresBlastemaAndNerve),
            Box::new(EpithelialRestitutionNoBioelectric),
            Box::new(AllBodyAxesRepresented),
        ]
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use pr4xis::category::validate::check_category_laws;
    use pr4xis::ontology::reasoning::causation::CausalCategory;
    use pr4xis::ontology::reasoning::opposition;
    use pr4xis::ontology::reasoning::taxonomy::TaxonomyCategory;

    // -- Axiom tests --

    #[test]
    fn test_injury_causes_restoration() {
        assert!(
            InjuryCausesRestoration.holds(),
            "{}",
            InjuryCausesRestoration.description()
        );
    }

    #[test]
    fn test_bioelectric_causes_pattern() {
        assert!(
            BioelectricCausesPattern.holds(),
            "{}",
            BioelectricCausesPattern.description()
        );
    }

    #[test]
    fn test_gap_junction_causes_collective_decision() {
        assert!(
            GapJunctionCausesCollectiveDecision.holds(),
            "{}",
            GapJunctionCausesCollectiveDecision.description()
        );
    }

    #[test]
    fn test_pattern_memory_is_not_regeneration_type() {
        assert!(
            PatternMemoryIsNotRegenerationType.holds(),
            "{}",
            PatternMemoryIsNotRegenerationType.description()
        );
    }

    #[test]
    fn test_bistability_is_patterning() {
        assert!(
            BistabilityIsPatterning.holds(),
            "{}",
            BistabilityIsPatterning.description()
        );
    }

    #[test]
    fn test_epimorphic_requires_blastema_and_nerve() {
        assert!(
            EpimorphicRequiresBlastemaAndNerve.holds(),
            "{}",
            EpimorphicRequiresBlastemaAndNerve.description()
        );
    }

    #[test]
    fn test_epithelial_restitution_no_bioelectric() {
        assert!(
            EpithelialRestitutionNoBioelectric.holds(),
            "{}",
            EpithelialRestitutionNoBioelectric.description()
        );
    }

    #[test]
    fn test_all_body_axes_represented() {
        assert!(
            AllBodyAxesRepresented.holds(),
            "{}",
            AllBodyAxesRepresented.description()
        );
    }

    // -- Category law tests --

    #[test]
    fn test_regeneration_category_laws() {
        check_category_laws::<RegenerationCategory>().unwrap();
    }

    #[test]
    fn test_taxonomy_category_laws() {
        check_category_laws::<TaxonomyCategory<RegenerationTaxonomy>>().unwrap();
    }

    #[test]
    fn test_causal_category_laws() {
        check_category_laws::<CausalCategory<RegenerationCauses>>().unwrap();
    }

    // -- Taxonomy tests --

    #[test]
    fn test_regeneration_types_are_regeneration_type() {
        use RegenerationEntity::*;
        for ty in [
            Epimorphic,
            Morphallactic,
            Compensatory,
            StemCellMediated,
            EpithelialRestitution,
        ] {
            assert!(
                taxonomy::is_a::<RegenerationTaxonomy>(&ty, &RegenerationType),
                "{:?} should be a RegenerationType",
                ty
            );
        }
    }

    #[test]
    fn test_axes_are_body_axis() {
        use RegenerationEntity::*;
        for axis in [AnteriorPosteriorAxis, DorsalVentralAxis, LeftRightAxis] {
            assert!(
                taxonomy::is_a::<RegenerationTaxonomy>(&axis, &BodyAxis),
                "{:?} should be a BodyAxis",
                axis
            );
        }
    }

    #[test]
    fn test_axes_are_pattern_concept_transitively() {
        use RegenerationEntity::*;
        // Axes -> BodyAxis -> PatternConcept (transitive)
        for axis in [AnteriorPosteriorAxis, DorsalVentralAxis, LeftRightAxis] {
            assert!(
                taxonomy::is_a::<RegenerationTaxonomy>(&axis, &PatternConcept),
                "{:?} should transitively be a PatternConcept",
                axis
            );
        }
    }

    #[test]
    fn test_structures_are_structure() {
        use RegenerationEntity::*;
        for s in [Blastema, WoundEpithelium, NerveSupply] {
            assert!(
                taxonomy::is_a::<RegenerationTaxonomy>(&s, &Structure),
                "{:?} should be a Structure",
                s
            );
        }
    }

    #[test]
    fn test_entity_count() {
        assert_eq!(RegenerationEntity::variants().len(), 19);
    }

    #[test]
    fn test_event_count() {
        assert_eq!(RegenerationEvent::variants().len(), 11);
    }

    // -- Causal chain tests --

    #[test]
    fn test_injury_causes_wound_closure() {
        use RegenerationEvent::*;
        let effects = causation::effects_of::<RegenerationCauses>(&Injury);
        assert!(effects.contains(&WoundClosure));
    }

    #[test]
    fn test_nerve_signaling_causes_blastema_formation() {
        use RegenerationEvent::*;
        let effects = causation::effects_of::<RegenerationCauses>(&NerveSignaling);
        assert!(effects.contains(&BlastemaFormation));
    }

    #[test]
    fn test_bioelectric_signal_reaches_restoration() {
        use RegenerationEvent::*;
        let effects = causation::effects_of::<RegenerationCauses>(&BioelectricSignal);
        assert!(
            effects.contains(&MorphologicalRestoration),
            "BioelectricSignal should transitively reach MorphologicalRestoration"
        );
    }

    #[test]
    fn test_gap_junction_reaches_restoration() {
        use RegenerationEvent::*;
        let effects = causation::effects_of::<RegenerationCauses>(&GapJunctionCommunication);
        assert!(
            effects.contains(&MorphologicalRestoration),
            "GapJunctionCommunication should transitively reach MorphologicalRestoration"
        );
    }

    // -- Quality tests --

    #[test]
    fn test_morphallactic_no_blastema() {
        use RegenerationEntity::*;
        assert_eq!(RequiresBlastema.get(&Morphallactic), Some(false));
    }

    #[test]
    fn test_compensatory_no_nerve_supply() {
        use RegenerationEntity::*;
        assert_eq!(RequiresNerveSupply.get(&Compensatory), Some(false));
    }

    #[test]
    fn test_anatomical_polarity_is_reversible() {
        use RegenerationEntity::*;
        assert_eq!(IsReversible.get(&AnatomicalPolarity), Some(true));
    }

    #[test]
    fn test_epithelial_restitution_is_fastest() {
        use RegenerationEntity::*;
        assert_eq!(
            RegenerationSpeed.get(&EpithelialRestitution),
            Some(RegenerationTimescale::Hours)
        );
    }

    #[test]
    fn test_epimorphic_requires_bioelectric() {
        use RegenerationEntity::*;
        assert_eq!(RequiresBioelectricSignal.get(&Epimorphic), Some(true));
    }

    #[test]
    fn test_ontology_validates() {
        RegenerationOntology::validate().unwrap();
    }

    #[test]
    fn test_regeneration_type_descendants_count() {
        use RegenerationEntity::*;
        let descendants = taxonomy::descendants::<RegenerationTaxonomy>(&RegenerationType);
        assert_eq!(descendants.len(), 5);
    }

    #[test]
    fn test_pattern_concept_descendants_include_axes() {
        use RegenerationEntity::*;
        let descendants = taxonomy::descendants::<RegenerationTaxonomy>(&PatternConcept);
        // PatternConcept descendants: TargetMorphology, AnatomicalPolarity, PatternMemory,
        // Bistability, BodyAxis, AnteriorPosteriorAxis, DorsalVentralAxis, LeftRightAxis
        assert!(descendants.contains(&BodyAxis));
        assert!(descendants.contains(&AnteriorPosteriorAxis));
        assert_eq!(descendants.len(), 8);
    }

    // -- Property-based tests (proptest) --

    use proptest::prelude::*;

    fn arb_regeneration_entity() -> impl Strategy<Value = RegenerationEntity> {
        (0..RegenerationEntity::variants().len()).prop_map(|i| RegenerationEntity::variants()[i])
    }

    proptest! {
        #[test]
        fn prop_regeneration_type_has_speed(entity in arb_regeneration_entity()) {
            // Every regeneration type has a defined speed
            if taxonomy::is_a::<RegenerationTaxonomy>(&entity, &RegenerationEntity::RegenerationType)
                && !matches!(entity, RegenerationEntity::RegenerationType)
            {
                prop_assert!(RegenerationSpeed.get(&entity).is_some());
            }
        }

        #[test]
        fn prop_taxonomy_reflexive(entity in arb_regeneration_entity()) {
            prop_assert!(taxonomy::is_a::<RegenerationTaxonomy>(&entity, &entity));
        }

        /// For any RegenerationEntity that is a RegenerationType,
        /// RequiresBlastema and RequiresBioelectricSignal are both defined (Some).
        #[test]
        fn prop_regeneration_type_qualities_defined(entity in arb_regeneration_entity()) {
            if taxonomy::is_a::<RegenerationTaxonomy>(
                &entity,
                &RegenerationEntity::RegenerationType,
            ) && entity != RegenerationEntity::RegenerationType
            {
                prop_assert!(
                    RequiresBlastema.get(&entity).is_some(),
                    "RequiresBlastema should be defined for RegenerationType {:?}",
                    entity
                );
                prop_assert!(
                    RequiresBioelectricSignal.get(&entity).is_some(),
                    "RequiresBioelectricSignal should be defined for RegenerationType {:?}",
                    entity
                );
            }
        }
    }

    // -- Literature axioms --

    /// Levin 2017 PMID:28538159: brief bioelectric intervention produces long-term
    /// stochastic editing of anatomy. PatternMemory and Bistability are pattern
    /// concepts, not regeneration types.
    #[test]
    fn test_literature_levin_2017_pattern_memory_bistability_are_pattern_concepts() {
        use RegenerationEntity::*;
        // PatternMemory is a PatternConcept, not a RegenerationType
        assert!(
            taxonomy::is_a::<RegenerationTaxonomy>(&PatternMemory, &PatternConcept),
            "Levin 2017: PatternMemory must be a PatternConcept"
        );
        assert!(
            !taxonomy::is_a::<RegenerationTaxonomy>(&PatternMemory, &RegenerationType),
            "Levin 2017: PatternMemory must NOT be a RegenerationType"
        );
        // Bistability is a PatternConcept, not a RegenerationType
        assert!(
            taxonomy::is_a::<RegenerationTaxonomy>(&Bistability, &PatternConcept),
            "Levin 2017: Bistability must be a PatternConcept"
        );
        assert!(
            !taxonomy::is_a::<RegenerationTaxonomy>(&Bistability, &RegenerationType),
            "Levin 2017: Bistability must NOT be a RegenerationType"
        );
    }

    #[test]
    fn test_all_regeneration_types_have_model_organism() {
        use RegenerationEntity::*;
        for ty in [
            Epimorphic,
            Morphallactic,
            Compensatory,
            StemCellMediated,
            EpithelialRestitution,
        ] {
            assert!(
                PrimaryModelOrganism.get(&ty).is_some(),
                "{:?} should have a primary model organism",
                ty
            );
        }
    }

    /// Singer 1952 (classic denervation experiments): epimorphic regeneration
    /// requires nerve supply.
    #[test]
    fn test_literature_singer_1952_epimorphic_requires_nerve() {
        use RegenerationEntity::*;
        assert_eq!(
            RequiresNerveSupply.get(&Epimorphic),
            Some(true),
            "Singer 1952: epimorphic regeneration requires nerve supply \
             (classic denervation experiments showed limb regeneration fails without nerves)"
        );
        // Also verify that NerveSignaling causally leads to BlastemaFormation
        use RegenerationEvent::*;
        let effects = causation::effects_of::<RegenerationCauses>(&NerveSignaling);
        assert!(
            effects.contains(&BlastemaFormation),
            "Singer 1952: nerve signaling must cause blastema formation"
        );
    }

    // -- Opposition tests --

    #[test]
    fn test_epimorphic_opposes_epithelial_restitution() {
        use RegenerationEntity::*;
        assert!(opposition::are_opposed::<RegenerationOpposition>(
            &Epimorphic,
            &EpithelialRestitution
        ));
        assert!(opposition::are_opposed::<RegenerationOpposition>(
            &EpithelialRestitution,
            &Epimorphic
        ));
    }

    #[test]
    fn test_blastema_opposes_wound_epithelium() {
        use RegenerationEntity::*;
        assert!(opposition::are_opposed::<RegenerationOpposition>(
            &Blastema,
            &WoundEpithelium
        ));
    }

    #[test]
    fn test_target_morphology_opposes_bistability() {
        use RegenerationEntity::*;
        assert!(opposition::are_opposed::<RegenerationOpposition>(
            &TargetMorphology,
            &Bistability
        ));
    }

    #[test]
    fn test_epimorphic_does_not_oppose_morphallactic() {
        use RegenerationEntity::*;
        assert!(!opposition::are_opposed::<RegenerationOpposition>(
            &Epimorphic,
            &Morphallactic
        ));
    }

    #[test]
    fn test_regeneration_opposites_query() {
        use RegenerationEntity::*;
        let opps = opposition::opposites::<RegenerationOpposition>(&Epimorphic);
        assert_eq!(opps, vec![EpithelialRestitution]);
    }
}
