//! Mechanotransduction ontology.
//!
//! Models the conversion of mechanical vibration into neural signals
//! in the cochlear hair cells.
//!
//! Key molecular players:
//! - TMC1/TMC2: MET channel pore-forming subunits (Pan et al. 2013)
//! - TMIE, LHFPL5/TMHS: MET channel auxiliary subunits
//! - CDH23, PCDH15: tip link proteins (cadherin-23, protocadherin-15)
//! - Prestin (SLC26A5): OHC electromotile protein (Zheng et al. 2000)
//! - KCNQ4: K+ channel in hair cells (Kubisch et al. 1999)
//!
//! Endocochlear potential: +80 mV in scala media (von Békésy 1952),
//! generated by stria vascularis, provides the driving force for MET.

use pr4xis::category::Entity;
use pr4xis::define_dense_category;
use pr4xis::ontology::reasoning::causation::{self, CausalDef};
use pr4xis::ontology::reasoning::mereology::{self, MereologyDef};
use pr4xis::ontology::reasoning::opposition::{self, OppositionDef};
use pr4xis::ontology::reasoning::taxonomy::{self, TaxonomyDef};
use pr4xis::ontology::{Axiom, Ontology, Quality};

// ---------------------------------------------------------------------------
// Entity
// ---------------------------------------------------------------------------

/// Every entity in the mechanotransduction domain.
#[allow(non_camel_case_types)]
#[derive(Debug, Copy, Clone, PartialEq, Eq, Hash, Entity)]
pub enum TransductionEntity {
    // Structural components
    Stereocilium,
    StereociliaBundle,
    TipLink,
    Kinocilium,
    CuticularPlate,
    // Tip link proteins
    Cadherin23,
    Protocadherin15,
    // MET channel complex
    METChannel,
    TMC1,
    TMC2,
    TMIE,
    LHFPL5,
    // Ion channels
    KCNQ4,
    CaV1_3,
    BKChannel,
    // Motor protein
    Prestin,
    // Ions and potentials
    Potassium,
    Calcium,
    Glutamate,
    EndocochlearPotential,
    ReceptorPotential,
    // Cellular events
    StereociliaDeflection,
    TipLinkTension,
    METChannelOpening,
    PotassiumInflux,
    CalciumInflux,
    Depolarization,
    GlutamateRelease,
    ActionPotential,
    // OHC-specific
    Electromotility,
    CochlearAmplification,
    // Abstract categories
    METComponent,
    IonChannel,
    TipLinkProtein,
    CellularSignal,
}

// ---------------------------------------------------------------------------
// Taxonomy (is-a)
// ---------------------------------------------------------------------------

/// Subsumption hierarchy for transduction entities.
pub struct TransductionTaxonomy;

impl TaxonomyDef for TransductionTaxonomy {
    type Entity = TransductionEntity;

    fn relations() -> Vec<(TransductionEntity, TransductionEntity)> {
        use TransductionEntity::*;
        vec![
            // MET channel components
            (TMC1, METComponent),
            (TMC2, METComponent),
            (TMIE, METComponent),
            (LHFPL5, METComponent),
            (METChannel, IonChannel),
            // Tip link proteins
            (Cadherin23, TipLinkProtein),
            (Protocadherin15, TipLinkProtein),
            // Ion channels
            (KCNQ4, IonChannel),
            (CaV1_3, IonChannel),
            (BKChannel, IonChannel),
            // Cellular signals
            (PotassiumInflux, CellularSignal),
            (CalciumInflux, CellularSignal),
            (Depolarization, CellularSignal),
            (GlutamateRelease, CellularSignal),
            (ActionPotential, CellularSignal),
            (ReceptorPotential, CellularSignal),
        ]
    }
}

// ---------------------------------------------------------------------------
// Mereology (has-a / part-whole)
// ---------------------------------------------------------------------------

/// Part-whole relationships for mechanotransduction.
///
/// Structural composition of the stereocilia bundle, tip links, and
/// the MET channel complex.
///
/// - Stereocilia bundle contains stereocilia, tip links, and kinocilium
/// - Tip link is composed of cadherin-23 and protocadherin-15
/// - MET channel complex contains TMC1, TMC2, TMIE, and LHFPL5
///
/// Kazmierczak et al. 2007; Pan et al. 2013.
pub struct TransductionMereology;

impl MereologyDef for TransductionMereology {
    type Entity = TransductionEntity;

    fn relations() -> Vec<(TransductionEntity, TransductionEntity)> {
        use TransductionEntity::*;
        vec![
            // Stereocilia bundle composition
            (StereociliaBundle, Stereocilium),
            (StereociliaBundle, TipLink),
            (StereociliaBundle, Kinocilium),
            // Tip link protein composition
            (TipLink, Cadherin23),
            (TipLink, Protocadherin15),
            // MET channel complex subunits
            (METChannel, TMC1),
            (METChannel, TMC2),
            (METChannel, TMIE),
            (METChannel, LHFPL5),
        ]
    }
}

// ---------------------------------------------------------------------------
// Causal graph
// ---------------------------------------------------------------------------

/// Causal events in the mechanoelectrical transduction cascade.
///
/// The canonical hair cell transduction chain:
/// Basilar membrane motion → stereocilia deflection → tip link tension →
/// MET channel opening → K+ influx (driven by EP) → depolarization →
/// Ca2+ entry → glutamate release → auditory nerve AP.
///
/// OHC branch: depolarization → prestin conformational change →
/// electromotility → cochlear amplification → enhanced BM motion.
///
/// Hudspeth 1989; Fettiplace & Kim 2014.
#[derive(Debug, Copy, Clone, PartialEq, Eq, Hash, Entity)]
pub enum TransductionCausalEvent {
    BasilarMembraneMotion,
    StereociliaBundleDeflection,
    TipLinkStretch,
    METChannelGating,
    PotassiumEntry,
    CellDepolarization,
    CalciumEntry,
    VesicleRelease,
    NerveActivation,
    // OHC amplification loop
    PrestiConformationChange,
    CellLengthChange,
    BasilarMembraneAmplification,
    // Adaptation
    SlowAdaptation,
    FastAdaptation,
}

/// Causal graph for hair cell mechanotransduction.
pub struct TransductionCausalGraph;

impl CausalDef for TransductionCausalGraph {
    type Entity = TransductionCausalEvent;

    fn relations() -> Vec<(TransductionCausalEvent, TransductionCausalEvent)> {
        use TransductionCausalEvent::*;
        vec![
            // Main transduction chain (IHC and OHC)
            (BasilarMembraneMotion, StereociliaBundleDeflection),
            (StereociliaBundleDeflection, TipLinkStretch),
            (TipLinkStretch, METChannelGating),
            (METChannelGating, PotassiumEntry),
            (PotassiumEntry, CellDepolarization),
            (CellDepolarization, CalciumEntry),
            // IHC: calcium → vesicle release → nerve
            (CalciumEntry, VesicleRelease),
            (VesicleRelease, NerveActivation),
            // OHC: depolarization → prestin → electromotility → amplification
            (CellDepolarization, PrestiConformationChange),
            (PrestiConformationChange, CellLengthChange),
            (CellLengthChange, BasilarMembraneAmplification),
            // Adaptation mechanisms (downstream effects, no feedback loop)
            (CalciumEntry, SlowAdaptation),
            (CalciumEntry, FastAdaptation),
        ]
    }
}

// ---------------------------------------------------------------------------
// Category
// ---------------------------------------------------------------------------

define_dense_category! {
    /// Discrete category over transduction entities.
    pub TransductionCategory {
        entity: TransductionEntity,
        relation: TransductionRelation,
    }
}

// ---------------------------------------------------------------------------
// Qualities
// ---------------------------------------------------------------------------

/// Resting membrane potential (mV) of relevant structures.
///
/// - Endolymph: +80 mV (endocochlear potential, von Békésy 1952)
/// - IHC resting: -45 mV (Russell & Sellick 1978)
/// - OHC resting: -70 mV (Dallos 1985)
/// - Combined driving force for K+: ~125 mV (EP + OHC Vrest)
#[derive(Debug, Clone)]
pub struct RestingPotential;

impl Quality for RestingPotential {
    type Individual = TransductionEntity;
    type Value = f64;

    fn get(&self, individual: &TransductionEntity) -> Option<f64> {
        use TransductionEntity::*;
        match individual {
            EndocochlearPotential => Some(80.0), // +80 mV, von Békésy 1952
            Potassium => Some(-90.0),            // Nernst potential for K+
            Calcium => Some(131.0),              // Nernst potential for Ca2+
            _ => None,
        }
    }
}

/// Tip link length (nm).
///
/// Cadherin-23 upper link: ~150-180 nm
/// Protocadherin-15 lower link: ~35-40 nm
/// Kazmierczak et al. 2007.
#[derive(Debug, Clone)]
pub struct TipLinkLength;

impl Quality for TipLinkLength {
    type Individual = TransductionEntity;
    type Value = f64;

    fn get(&self, individual: &TransductionEntity) -> Option<f64> {
        use TransductionEntity::*;
        match individual {
            Cadherin23 => Some(170.0),     // nm, upper portion
            Protocadherin15 => Some(37.0), // nm, lower portion
            TipLink => Some(207.0),        // nm, total length
            _ => None,
        }
    }
}

/// Conductance of the MET channel (pS).
///
/// ~100-300 pS depending on hair cell position along cochlea.
/// Beurg et al. 2006; Fettiplace & Kim 2014.
#[derive(Debug, Clone)]
pub struct ChannelConductance;

impl Quality for ChannelConductance {
    type Individual = TransductionEntity;
    type Value = f64;

    fn get(&self, individual: &TransductionEntity) -> Option<f64> {
        use TransductionEntity::*;
        match individual {
            METChannel => Some(150.0), // pS, average
            TMC1 => Some(150.0),       // pS, main pore
            KCNQ4 => Some(10.0),       // pS, K+ repolarization
            BKChannel => Some(250.0),  // pS, large-conductance K+
            _ => None,
        }
    }
}

/// Whether this entity is specific to outer hair cells.
#[derive(Debug, Clone)]
pub struct IsOHCSpecific;

impl Quality for IsOHCSpecific {
    type Individual = TransductionEntity;
    type Value = bool;

    fn get(&self, individual: &TransductionEntity) -> Option<bool> {
        use TransductionEntity::*;
        Some(matches!(
            individual,
            Prestin | Electromotility | CochlearAmplification
        ))
    }
}

// ---------------------------------------------------------------------------
// Opposition
// ---------------------------------------------------------------------------

/// Opposition pairs in transduction.
///
/// - Depolarization ↔ ReceptorPotential: onset vs sustained
/// - PotassiumInflux ↔ CalciumInflux: main current vs signaling current
/// - Electromotility ↔ ActionPotential: OHC output vs IHC output
pub struct TransductionOpposition;

impl OppositionDef for TransductionOpposition {
    type Entity = TransductionEntity;

    fn pairs() -> Vec<(TransductionEntity, TransductionEntity)> {
        use TransductionEntity::*;
        vec![
            (PotassiumInflux, CalciumInflux),
            (Electromotility, ActionPotential),
        ]
    }
}

// ---------------------------------------------------------------------------
// Axioms
// ---------------------------------------------------------------------------

/// Taxonomy is a DAG.
pub struct TransductionTaxonomyIsDAG;

impl Axiom for TransductionTaxonomyIsDAG {
    fn description(&self) -> &str {
        "transduction taxonomy is a directed acyclic graph"
    }

    fn holds(&self) -> bool {
        taxonomy::NoCycles::<TransductionTaxonomy>::new().holds()
    }
}

/// Mereology is a DAG.
pub struct TransductionMereologyIsDAG;

impl Axiom for TransductionMereologyIsDAG {
    fn description(&self) -> &str {
        "transduction mereology is a directed acyclic graph"
    }

    fn holds(&self) -> bool {
        mereology::NoCycles::<TransductionMereology>::new().holds()
    }
}

/// Stereocilia bundle transitively contains tip link proteins.
///
/// StereociliaBundle has-a TipLink, which has-a Cadherin23 and Protocadherin15.
/// Kazmierczak et al. 2007.
pub struct BundleContainsTipLinkProteins;

impl Axiom for BundleContainsTipLinkProteins {
    fn description(&self) -> &str {
        "stereocilia bundle transitively contains cadherin-23 and protocadherin-15"
    }

    fn holds(&self) -> bool {
        use TransductionEntity::*;
        let parts = mereology::parts_of::<TransductionMereology>(&StereociliaBundle);
        parts.contains(&Cadherin23) && parts.contains(&Protocadherin15)
    }
}

/// TMC1 and TMC2 are MET channel components.
///
/// Pan et al. 2013; Kawashima et al. 2011.
pub struct TMCsAreMETComponents;

impl Axiom for TMCsAreMETComponents {
    fn description(&self) -> &str {
        "TMC1 and TMC2 are components of the MET channel"
    }

    fn holds(&self) -> bool {
        use TransductionEntity::*;
        taxonomy::is_a::<TransductionTaxonomy>(&TMC1, &METComponent)
            && taxonomy::is_a::<TransductionTaxonomy>(&TMC2, &METComponent)
    }
}

/// Tip link is composed of CDH23 and PCDH15.
///
/// Kazmierczak et al. 2007; Siemens et al. 2004.
pub struct TipLinkProteins;

impl Axiom for TipLinkProteins {
    fn description(&self) -> &str {
        "cadherin-23 and protocadherin-15 are tip link proteins"
    }

    fn holds(&self) -> bool {
        use TransductionEntity::*;
        taxonomy::is_a::<TransductionTaxonomy>(&Cadherin23, &TipLinkProtein)
            && taxonomy::is_a::<TransductionTaxonomy>(&Protocadherin15, &TipLinkProtein)
    }
}

/// Basilar membrane motion transitively causes nerve activation.
///
/// The complete transduction chain.
/// Hudspeth 1989; Fettiplace & Kim 2014.
pub struct BMMotionCausesNerveActivation;

impl Axiom for BMMotionCausesNerveActivation {
    fn description(&self) -> &str {
        "basilar membrane motion transitively causes nerve activation"
    }

    fn holds(&self) -> bool {
        use TransductionCausalEvent::*;
        let effects = causation::effects_of::<TransductionCausalGraph>(&BasilarMembraneMotion);
        effects.contains(&NerveActivation)
    }
}

/// Depolarization causes prestin conformational change (OHC amplification).
///
/// Zheng et al. 2000; Dallos 1992.
pub struct DepolarizationCausesElectromotility;

impl Axiom for DepolarizationCausesElectromotility {
    fn description(&self) -> &str {
        "cell depolarization causes prestin conformational change in OHC"
    }

    fn holds(&self) -> bool {
        use TransductionCausalEvent::*;
        let effects = causation::effects_of::<TransductionCausalGraph>(&CellDepolarization);
        effects.contains(&PrestiConformationChange)
    }
}

/// Endocochlear potential is positive (provides driving force for MET).
///
/// von Békésy 1952: +80 mV in scala media.
pub struct EndocochlearPotentialIsPositive;

impl Axiom for EndocochlearPotentialIsPositive {
    fn description(&self) -> &str {
        "endocochlear potential is positive (+80 mV)"
    }

    fn holds(&self) -> bool {
        use TransductionEntity::*;
        RestingPotential.get(&EndocochlearPotential).unwrap() > 0.0
    }
}

/// Prestin is OHC-specific.
///
/// Zheng et al. 2000.
pub struct PrestiIsOHCSpecific;

impl Axiom for PrestiIsOHCSpecific {
    fn description(&self) -> &str {
        "prestin is specific to outer hair cells"
    }

    fn holds(&self) -> bool {
        IsOHCSpecific.get(&TransductionEntity::Prestin) == Some(true)
    }
}

/// Causal graph is asymmetric.
pub struct TransductionCausalGraphIsAsymmetric;

impl Axiom for TransductionCausalGraphIsAsymmetric {
    fn description(&self) -> &str {
        "transduction causal graph is asymmetric"
    }

    fn holds(&self) -> bool {
        causation::Asymmetric::<TransductionCausalGraph>::new().holds()
    }
}

/// Opposition is symmetric.
pub struct TransductionOppositionSymmetric;

impl Axiom for TransductionOppositionSymmetric {
    fn description(&self) -> &str {
        "transduction opposition is symmetric"
    }

    fn holds(&self) -> bool {
        opposition::Symmetric::<TransductionOpposition>::new().holds()
    }
}

/// Opposition is irreflexive.
pub struct TransductionOppositionIrreflexive;

impl Axiom for TransductionOppositionIrreflexive {
    fn description(&self) -> &str {
        "transduction opposition is irreflexive"
    }

    fn holds(&self) -> bool {
        opposition::Irreflexive::<TransductionOpposition>::new().holds()
    }
}

// ---------------------------------------------------------------------------
// Ontology
// ---------------------------------------------------------------------------

/// Top-level mechanotransduction ontology.
pub struct TransductionOntology;

impl Ontology for TransductionOntology {
    type Cat = TransductionCategory;
    type Qual = ChannelConductance;

    fn axioms() -> Vec<Box<dyn Axiom>> {
        vec![
            Box::new(TransductionTaxonomyIsDAG),
            Box::new(TransductionMereologyIsDAG),
            Box::new(BundleContainsTipLinkProteins),
            Box::new(TMCsAreMETComponents),
            Box::new(TipLinkProteins),
            Box::new(BMMotionCausesNerveActivation),
            Box::new(DepolarizationCausesElectromotility),
            Box::new(EndocochlearPotentialIsPositive),
            Box::new(PrestiIsOHCSpecific),
            Box::new(TransductionCausalGraphIsAsymmetric),
            Box::new(TransductionOppositionSymmetric),
            Box::new(TransductionOppositionIrreflexive),
        ]
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use pr4xis::category::Category;
    use pr4xis::category::validate::check_category_laws;
    use pr4xis::ontology::reasoning::causation::CausalCategory;
    use pr4xis::ontology::reasoning::mereology::MereologyCategory;
    use pr4xis::ontology::reasoning::taxonomy::TaxonomyCategory;
    use proptest::prelude::*;

    // -- Axiom tests --

    #[test]
    fn test_taxonomy_is_dag() {
        assert!(
            TransductionTaxonomyIsDAG.holds(),
            "{}",
            TransductionTaxonomyIsDAG.description()
        );
    }

    #[test]
    fn test_mereology_is_dag() {
        assert!(
            TransductionMereologyIsDAG.holds(),
            "{}",
            TransductionMereologyIsDAG.description()
        );
    }

    #[test]
    fn test_bundle_contains_tip_link_proteins() {
        assert!(
            BundleContainsTipLinkProteins.holds(),
            "{}",
            BundleContainsTipLinkProteins.description()
        );
    }

    #[test]
    fn test_tmcs_are_met_components() {
        assert!(
            TMCsAreMETComponents.holds(),
            "{}",
            TMCsAreMETComponents.description()
        );
    }

    #[test]
    fn test_tip_link_proteins() {
        assert!(TipLinkProteins.holds(), "{}", TipLinkProteins.description());
    }

    #[test]
    fn test_bm_motion_causes_nerve_activation() {
        assert!(
            BMMotionCausesNerveActivation.holds(),
            "{}",
            BMMotionCausesNerveActivation.description()
        );
    }

    #[test]
    fn test_depolarization_causes_electromotility() {
        assert!(
            DepolarizationCausesElectromotility.holds(),
            "{}",
            DepolarizationCausesElectromotility.description()
        );
    }

    #[test]
    fn test_endocochlear_potential_is_positive() {
        assert!(
            EndocochlearPotentialIsPositive.holds(),
            "{}",
            EndocochlearPotentialIsPositive.description()
        );
    }

    #[test]
    fn test_prestin_is_ohc_specific() {
        assert!(
            PrestiIsOHCSpecific.holds(),
            "{}",
            PrestiIsOHCSpecific.description()
        );
    }

    #[test]
    fn test_causal_graph_asymmetric() {
        assert!(
            TransductionCausalGraphIsAsymmetric.holds(),
            "{}",
            TransductionCausalGraphIsAsymmetric.description()
        );
    }

    #[test]
    fn test_opposition_symmetric() {
        assert!(
            TransductionOppositionSymmetric.holds(),
            "{}",
            TransductionOppositionSymmetric.description()
        );
    }

    #[test]
    fn test_opposition_irreflexive() {
        assert!(
            TransductionOppositionIrreflexive.holds(),
            "{}",
            TransductionOppositionIrreflexive.description()
        );
    }

    // -- Category law tests --

    #[test]
    fn test_transduction_category_laws() {
        check_category_laws::<TransductionCategory>().unwrap();
    }

    #[test]
    fn test_taxonomy_category_laws() {
        check_category_laws::<TaxonomyCategory<TransductionTaxonomy>>().unwrap();
    }

    #[test]
    fn test_causal_category_laws() {
        check_category_laws::<CausalCategory<TransductionCausalGraph>>().unwrap();
    }

    #[test]
    fn test_mereology_category_laws() {
        check_category_laws::<MereologyCategory<TransductionMereology>>().unwrap();
    }

    // -- Causal chain tests --

    #[test]
    fn test_full_transduction_chain_length() {
        use TransductionCausalEvent::*;
        let effects = causation::effects_of::<TransductionCausalGraph>(&BasilarMembraneMotion);
        // BM → stereocilia → tip link → MET → K+ → depol → Ca2+ → vesicle → nerve
        // Plus: depol → prestin → length → amplification
        // Plus: Ca2+ → slow/fast adaptation → MET
        assert!(
            effects.len() >= 10,
            "BM motion should have at least 10 transitive effects, got {}",
            effects.len()
        );
    }

    #[test]
    fn test_ohc_amplification_loop() {
        use TransductionCausalEvent::*;
        let effects = causation::effects_of::<TransductionCausalGraph>(&CellDepolarization);
        assert!(effects.contains(&PrestiConformationChange));
        assert!(effects.contains(&CellLengthChange));
        assert!(effects.contains(&BasilarMembraneAmplification));
    }

    #[test]
    fn test_calcium_triggers_adaptation() {
        use TransductionCausalEvent::*;
        let effects = causation::effects_of::<TransductionCausalGraph>(&CalciumEntry);
        assert!(effects.contains(&SlowAdaptation));
        assert!(effects.contains(&FastAdaptation));
    }

    // -- Quality tests --

    #[test]
    fn test_endocochlear_potential_value() {
        assert_eq!(
            RestingPotential.get(&TransductionEntity::EndocochlearPotential),
            Some(80.0)
        );
    }

    #[test]
    fn test_tip_link_total_length() {
        assert_eq!(TipLinkLength.get(&TransductionEntity::TipLink), Some(207.0));
    }

    #[test]
    fn test_met_channel_conductance() {
        assert_eq!(
            ChannelConductance.get(&TransductionEntity::METChannel),
            Some(150.0)
        );
    }

    #[test]
    fn test_prestin_is_ohc_specific_quality() {
        assert_eq!(IsOHCSpecific.get(&TransductionEntity::Prestin), Some(true));
    }

    #[test]
    fn test_potassium_influx_is_not_ohc_specific() {
        assert_eq!(
            IsOHCSpecific.get(&TransductionEntity::PotassiumInflux),
            Some(false)
        );
    }

    #[test]
    fn test_entity_count() {
        assert_eq!(TransductionEntity::variants().len(), 35);
    }

    #[test]
    fn test_ontology_validates() {
        TransductionOntology::validate().unwrap();
    }

    fn arb_transduction_entity() -> impl Strategy<Value = TransductionEntity> {
        (0..TransductionEntity::variants().len()).prop_map(|i| TransductionEntity::variants()[i])
    }

    proptest! {
        #[test]
        fn prop_taxonomy_reflexive(entity in arb_transduction_entity()) {
            prop_assert!(taxonomy::is_a::<TransductionTaxonomy>(&entity, &entity));
        }
    }
}
