//! Mechanotransduction ontology.
//!
//! Models the conversion of mechanical vibration into neural signals
//! in the cochlear hair cells.
//!
//! Key molecular players:
//! - TMC1/TMC2: MET channel pore-forming subunits (Pan et al. 2013)
//! - TMIE, LHFPL5/TMHS: MET channel auxiliary subunits
//! - CDH23, PCDH15: tip link proteins (cadherin-23, protocadherin-15)
//! - Prestin (SLC26A5): OHC electromotile protein (Zheng et al. 2000)
//! - KCNQ4: K+ channel in hair cells (Kubisch et al. 1999)
//!
//! Endocochlear potential: +80 mV in scala media (von Bekesy 1952),
//! generated by stria vascularis, provides the driving force for MET.

#[allow(unused_imports)]
use alloc::{boxed::Box, format, string::String, string::ToString, vec, vec::Vec};

use pr4xis::category::Concept;
use pr4xis::define_ontology;
use pr4xis::ontology::reasoning::causation;
use pr4xis::ontology::reasoning::mereology;
use pr4xis::ontology::reasoning::taxonomy;
use pr4xis::ontology::{Axiom, Ontology, Quality};

#[allow(non_camel_case_types)]
#[derive(Debug, Copy, Clone, PartialEq, Eq, Hash, Concept)]
pub enum TransductionEntity {
    Stereocilium,
    StereociliaBundle,
    TipLink,
    Kinocilium,
    CuticularPlate,
    Cadherin23,
    Protocadherin15,
    METChannel,
    TMC1,
    TMC2,
    TMIE,
    LHFPL5,
    KCNQ4,
    CaV1_3,
    BKChannel,
    Prestin,
    Potassium,
    Calcium,
    Glutamate,
    EndocochlearPotential,
    ReceptorPotential,
    StereociliaDeflection,
    TipLinkTension,
    METChannelOpening,
    PotassiumInflux,
    CalciumInflux,
    Depolarization,
    GlutamateRelease,
    ActionPotential,
    Electromotility,
    CochlearAmplification,
    METComponent,
    IonChannel,
    TipLinkProtein,
    CellularSignal,
}
#[derive(Debug, Copy, Clone, PartialEq, Eq, Hash, Concept)]
pub enum TransductionCausalEvent {
    BasilarMembraneMotion,
    StereociliaBundleDeflection,
    TipLinkStretch,
    METChannelGating,
    PotassiumEntry,
    CellDepolarization,
    CalciumEntry,
    VesicleRelease,
    NerveActivation,
    PrestiConformationChange,
    CellLengthChange,
    BasilarMembraneAmplification,
    SlowAdaptation,
    FastAdaptation,
}
define_ontology! {
    /// Discrete category over transduction entities.
    pub TransductionOntology for TransductionCategory {
        entity: TransductionEntity, relation: TransductionRelation,
        being: Process,
        source: "Hudspeth (1989); Fettiplace & Kim (2014)",
        taxonomy: TransductionTaxonomy [
            (TMC1, METComponent), (TMC2, METComponent), (TMIE, METComponent), (LHFPL5, METComponent),
            (METChannel, IonChannel), (Cadherin23, TipLinkProtein), (Protocadherin15, TipLinkProtein),
            (KCNQ4, IonChannel), (CaV1_3, IonChannel), (BKChannel, IonChannel),
            (PotassiumInflux, CellularSignal), (CalciumInflux, CellularSignal), (Depolarization, CellularSignal), (GlutamateRelease, CellularSignal), (ActionPotential, CellularSignal), (ReceptorPotential, CellularSignal),
        ],
        mereology: TransductionMereology [
            (StereociliaBundle, Stereocilium), (StereociliaBundle, TipLink), (StereociliaBundle, Kinocilium),
            (TipLink, Cadherin23), (TipLink, Protocadherin15),
            (METChannel, TMC1), (METChannel, TMC2), (METChannel, TMIE), (METChannel, LHFPL5),
        ],
        causation: TransductionCausalGraph for TransductionCausalEvent [
            (BasilarMembraneMotion, StereociliaBundleDeflection), (StereociliaBundleDeflection, TipLinkStretch), (TipLinkStretch, METChannelGating), (METChannelGating, PotassiumEntry), (PotassiumEntry, CellDepolarization), (CellDepolarization, CalciumEntry), (CalciumEntry, VesicleRelease), (VesicleRelease, NerveActivation), (CellDepolarization, PrestiConformationChange), (PrestiConformationChange, CellLengthChange), (CellLengthChange, BasilarMembraneAmplification), (CalciumEntry, SlowAdaptation), (CalciumEntry, FastAdaptation),
        ],
        opposition: TransductionOpposition [ (PotassiumInflux, CalciumInflux), (Electromotility, ActionPotential) ],
    }
}
#[derive(Debug, Clone)]
pub struct RestingPotential;
impl Quality for RestingPotential {
    type Individual = TransductionEntity;
    type Value = f64;
    fn get(&self, individual: &TransductionEntity) -> Option<f64> {
        use TransductionEntity::*;
        match individual {
            EndocochlearPotential => Some(80.0),
            Potassium => Some(-90.0),
            Calcium => Some(131.0),
            _ => None,
        }
    }
}
#[derive(Debug, Clone)]
pub struct TipLinkLength;
impl Quality for TipLinkLength {
    type Individual = TransductionEntity;
    type Value = f64;
    fn get(&self, individual: &TransductionEntity) -> Option<f64> {
        use TransductionEntity::*;
        match individual {
            Cadherin23 => Some(170.0),
            Protocadherin15 => Some(37.0),
            TipLink => Some(207.0),
            _ => None,
        }
    }
}
#[derive(Debug, Clone)]
pub struct ChannelConductance;
impl Quality for ChannelConductance {
    type Individual = TransductionEntity;
    type Value = f64;
    fn get(&self, individual: &TransductionEntity) -> Option<f64> {
        use TransductionEntity::*;
        match individual {
            METChannel => Some(150.0),
            TMC1 => Some(150.0),
            KCNQ4 => Some(10.0),
            BKChannel => Some(250.0),
            _ => None,
        }
    }
}
#[derive(Debug, Clone)]
pub struct IsOHCSpecific;
impl Quality for IsOHCSpecific {
    type Individual = TransductionEntity;
    type Value = bool;
    fn get(&self, individual: &TransductionEntity) -> Option<bool> {
        use TransductionEntity::*;
        Some(matches!(
            individual,
            Prestin | Electromotility | CochlearAmplification
        ))
    }
}

pub struct BundleContainsTipLinkProteins;
impl Axiom for BundleContainsTipLinkProteins {
    fn description(&self) -> &str {
        "stereocilia bundle transitively contains cadherin-23 and protocadherin-15"
    }
    fn holds(&self) -> bool {
        use TransductionEntity::*;
        let parts = mereology::parts_of::<TransductionMereology>(&StereociliaBundle);
        parts.contains(&Cadherin23) && parts.contains(&Protocadherin15)
    }
}
pr4xis::register_axiom!(BundleContainsTipLinkProteins);
pub struct TMCsAreMETComponents;
impl Axiom for TMCsAreMETComponents {
    fn description(&self) -> &str {
        "TMC1 and TMC2 are components of the MET channel"
    }
    fn holds(&self) -> bool {
        use TransductionEntity::*;
        taxonomy::is_a::<TransductionTaxonomy>(&TMC1, &METComponent)
            && taxonomy::is_a::<TransductionTaxonomy>(&TMC2, &METComponent)
    }
}
pr4xis::register_axiom!(TMCsAreMETComponents);
pub struct TipLinkProteins;
impl Axiom for TipLinkProteins {
    fn description(&self) -> &str {
        "cadherin-23 and protocadherin-15 are tip link proteins"
    }
    fn holds(&self) -> bool {
        use TransductionEntity::*;
        taxonomy::is_a::<TransductionTaxonomy>(&Cadherin23, &TipLinkProtein)
            && taxonomy::is_a::<TransductionTaxonomy>(&Protocadherin15, &TipLinkProtein)
    }
}
pr4xis::register_axiom!(TipLinkProteins);
pub struct BMMotionCausesNerveActivation;
impl Axiom for BMMotionCausesNerveActivation {
    fn description(&self) -> &str {
        "basilar membrane motion transitively causes nerve activation"
    }
    fn holds(&self) -> bool {
        use TransductionCausalEvent::*;
        causation::effects_of::<TransductionCausalGraph>(&BasilarMembraneMotion)
            .contains(&NerveActivation)
    }
}
pr4xis::register_axiom!(BMMotionCausesNerveActivation);
pub struct DepolarizationCausesElectromotility;
impl Axiom for DepolarizationCausesElectromotility {
    fn description(&self) -> &str {
        "cell depolarization causes prestin conformational change in OHC"
    }
    fn holds(&self) -> bool {
        use TransductionCausalEvent::*;
        causation::effects_of::<TransductionCausalGraph>(&CellDepolarization)
            .contains(&PrestiConformationChange)
    }
}
pr4xis::register_axiom!(DepolarizationCausesElectromotility);
pub struct EndocochlearPotentialIsPositive;
impl Axiom for EndocochlearPotentialIsPositive {
    fn description(&self) -> &str {
        "endocochlear potential is positive (+80 mV)"
    }
    fn holds(&self) -> bool {
        RestingPotential
            .get(&TransductionEntity::EndocochlearPotential)
            .unwrap()
            > 0.0
    }
}
pr4xis::register_axiom!(EndocochlearPotentialIsPositive);
pub struct PrestiIsOHCSpecific;
impl Axiom for PrestiIsOHCSpecific {
    fn description(&self) -> &str {
        "prestin is specific to outer hair cells"
    }
    fn holds(&self) -> bool {
        IsOHCSpecific.get(&TransductionEntity::Prestin) == Some(true)
    }
}
pr4xis::register_axiom!(PrestiIsOHCSpecific);

impl Ontology for TransductionOntology {
    type Cat = TransductionCategory;
    type Qual = ChannelConductance;
    fn structural_axioms() -> Vec<Box<dyn Axiom>> {
        Self::generated_structural_axioms()
    }
    fn domain_axioms() -> Vec<Box<dyn Axiom>> {
        vec![
            Box::new(BundleContainsTipLinkProteins),
            Box::new(TMCsAreMETComponents),
            Box::new(TipLinkProteins),
            Box::new(BMMotionCausesNerveActivation),
            Box::new(DepolarizationCausesElectromotility),
            Box::new(EndocochlearPotentialIsPositive),
            Box::new(PrestiIsOHCSpecific),
        ]
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use pr4xis::category::validate::check_category_laws;
    use pr4xis::ontology::reasoning::causation::CausalCategory;
    use pr4xis::ontology::reasoning::mereology::MereologyCategory;
    use pr4xis::ontology::reasoning::taxonomy::TaxonomyCategory;
    use proptest::prelude::*;
    #[test]
    fn test_bundle_contains_tip_link_proteins() {
        assert!(BundleContainsTipLinkProteins.holds());
    }
    #[test]
    fn test_tmcs_are_met_components() {
        assert!(TMCsAreMETComponents.holds());
    }
    #[test]
    fn test_tip_link_proteins() {
        assert!(TipLinkProteins.holds());
    }
    #[test]
    fn test_bm_motion_causes_nerve_activation() {
        assert!(BMMotionCausesNerveActivation.holds());
    }
    #[test]
    fn test_depolarization_causes_electromotility() {
        assert!(DepolarizationCausesElectromotility.holds());
    }
    #[test]
    fn test_endocochlear_potential_is_positive() {
        assert!(EndocochlearPotentialIsPositive.holds());
    }
    #[test]
    fn test_prestin_is_ohc_specific() {
        assert!(PrestiIsOHCSpecific.holds());
    }
    #[test]
    fn test_transduction_category_laws() {
        check_category_laws::<TransductionCategory>().unwrap();
    }
    #[test]
    fn test_taxonomy_category_laws() {
        check_category_laws::<TaxonomyCategory<TransductionTaxonomy>>().unwrap();
    }
    #[test]
    fn test_causal_category_laws() {
        check_category_laws::<CausalCategory<TransductionCausalGraph>>().unwrap();
    }
    #[test]
    fn test_mereology_category_laws() {
        check_category_laws::<MereologyCategory<TransductionMereology>>().unwrap();
    }
    #[test]
    fn test_full_transduction_chain_length() {
        use TransductionCausalEvent::*;
        let effects = causation::effects_of::<TransductionCausalGraph>(&BasilarMembraneMotion);
        assert!(effects.len() >= 10);
    }
    #[test]
    fn test_ohc_amplification_loop() {
        use TransductionCausalEvent::*;
        let effects = causation::effects_of::<TransductionCausalGraph>(&CellDepolarization);
        assert!(effects.contains(&PrestiConformationChange));
        assert!(effects.contains(&CellLengthChange));
        assert!(effects.contains(&BasilarMembraneAmplification));
    }
    #[test]
    fn test_calcium_triggers_adaptation() {
        use TransductionCausalEvent::*;
        let effects = causation::effects_of::<TransductionCausalGraph>(&CalciumEntry);
        assert!(effects.contains(&SlowAdaptation));
        assert!(effects.contains(&FastAdaptation));
    }
    #[test]
    fn test_endocochlear_potential_value() {
        assert_eq!(
            RestingPotential.get(&TransductionEntity::EndocochlearPotential),
            Some(80.0)
        );
    }
    #[test]
    fn test_tip_link_total_length() {
        assert_eq!(TipLinkLength.get(&TransductionEntity::TipLink), Some(207.0));
    }
    #[test]
    fn test_met_channel_conductance() {
        assert_eq!(
            ChannelConductance.get(&TransductionEntity::METChannel),
            Some(150.0)
        );
    }
    #[test]
    fn test_prestin_is_ohc_specific_quality() {
        assert_eq!(IsOHCSpecific.get(&TransductionEntity::Prestin), Some(true));
    }
    #[test]
    fn test_potassium_influx_is_not_ohc_specific() {
        assert_eq!(
            IsOHCSpecific.get(&TransductionEntity::PotassiumInflux),
            Some(false)
        );
    }
    #[test]
    fn test_entity_count() {
        assert_eq!(TransductionEntity::variants().len(), 35);
    }
    #[test]
    fn test_ontology_validates() {
        TransductionOntology::validate().unwrap();
    }
    fn arb_transduction_entity() -> impl Strategy<Value = TransductionEntity> {
        (0..TransductionEntity::variants().len()).prop_map(|i| TransductionEntity::variants()[i])
    }
    proptest! { #[test] fn prop_taxonomy_reflexive(entity in arb_transduction_entity()) { prop_assert!(taxonomy::is_a::<TransductionTaxonomy>(&entity, &entity)); } }
}
