#[allow(unused_imports)]
use alloc::{boxed::Box, format, string::String, string::ToString, vec, vec::Vec};

use pr4xis::category::Concept;
use pr4xis::define_ontology;
use pr4xis::ontology::{Ontology, Quality};

// Provenance ontology — tracking the origin and history of knowledge.
//
// Grounded in W3C PROV-O (PROV Ontology, 2013):
//   https://www.w3.org/TR/prov-o/
//
// PROV-O defines three core concepts:
//   Entity — a thing (document, dataset, ontology, concept)
//   Activity — something that happens (a commit, a build, a derivation)
//   Agent — something that bears responsibility (a person, a tool, a process)
//
// Extended with version control concepts relevant to praxis:
//   Repository, Commit, Branch, Tag, Version — the lifecycle of knowledge artifacts
//
// This ontology lets praxis know WHERE each concept came from:
//   - Which paper defines it
//   - Which commit introduced it
//   - Which version of which spec
//   - Who authored the ontology
//
// References:
// - W3C PROV-O (2013) — https://www.w3.org/TR/prov-o/
// - W3C PROV-DM (2013) — https://www.w3.org/TR/prov-dm/

/// Core provenance concepts, aligned with W3C PROV-O.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Concept)]
pub enum ProvenanceConcept {
    // === PROV-O core (W3C §3.1) ===
    /// prov:Entity — a thing with provenance (an ontology, a document, a dataset).
    Artifact,
    /// prov:Activity — something that produces or transforms artifacts (a commit, a build).
    Activity,
    /// prov:Agent — bearer of responsibility (a person, a tool, a CI system).
    Agent,

    // === Version control ===
    /// A source code repository.
    Repository,
    /// A commit — an atomic change to a repository.
    Commit,
    /// A branch — a named line of development.
    Branch,
    /// A tag — a named point in history (e.g. v1.0).
    Tag,
    /// A version — a semantic version identifier.
    Version,

    // === Knowledge sources ===
    /// An academic paper or specification that defines concepts.
    Source,
    /// A specific section or definition within a source.
    Citation,
}

define_ontology! {
    pub ProvenanceOntology for ProvenanceCategory {
        concepts: ProvenanceConcept,
        relation: ProvenanceRelation,
        kind: ProvenanceRelationKind,
        kinds: [
            /// prov:wasGeneratedBy — Artifact was generated by Activity.
            WasGeneratedBy,
            /// prov:wasDerivedFrom — Artifact was derived from another Artifact.
            WasDerivedFrom,
            /// prov:wasAttributedTo — Artifact was attributed to Agent.
            WasAttributedTo,
            /// prov:wasAssociatedWith — Activity was associated with Agent.
            WasAssociatedWith,
            /// prov:used — Activity used Artifact.
            Used,
            /// Commit belongs to Repository.
            BelongsTo,
            /// Branch points to Commit.
            PointsTo,
            /// Tag marks a Commit.
            Marks,
            /// Artifact is defined by Source (academic paper, spec).
            DefinedBy,
            /// Citation references a specific part of Source.
            References,
            /// Version identifies an Artifact.
            Identifies,
        ],
        edges: [
            // PROV-O core relations
            (Artifact, Activity, WasGeneratedBy),
            (Artifact, Artifact, WasDerivedFrom),
            (Artifact, Agent, WasAttributedTo),
            (Activity, Agent, WasAssociatedWith),
            (Activity, Artifact, Used),
            // Version control
            (Commit, Repository, BelongsTo),
            (Branch, Commit, PointsTo),
            (Tag, Commit, Marks),
            (Version, Artifact, Identifies),
            // Knowledge sources
            (Artifact, Source, DefinedBy),
            (Citation, Source, References),
        ],
        composed: [
            (Artifact, Agent),
            (Activity, Artifact),
            (Commit, Artifact),
            (Branch, Repository),
            (Tag, Repository),
        ],
        being: AbstractObject,
        source: "W3C PROV-O (2013)",
    }
}

/// Whether a provenance concept is from the W3C PROV-O core (vs. extension).
#[derive(Debug, Clone)]
pub struct IsProvOCore;

impl Quality for IsProvOCore {
    type Individual = ProvenanceConcept;
    type Value = bool;

    fn get(&self, individual: &ProvenanceConcept) -> Option<bool> {
        match individual {
            ProvenanceConcept::Artifact => Some(true),
            ProvenanceConcept::Activity => Some(true),
            ProvenanceConcept::Agent => Some(true),
            _ => Some(false),
        }
    }
}

impl Ontology for ProvenanceOntology {
    type Cat = ProvenanceCategory;
    type Qual = IsProvOCore;

    fn structural_axioms() -> Vec<Box<dyn pr4xis::ontology::Axiom>> {
        Self::generated_structural_axioms()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use pr4xis::category::validate::check_category_laws;

    #[test]
    fn category_laws() {
        check_category_laws::<ProvenanceCategory>().unwrap();
    }

    #[test]
    fn ontology_validates() {
        ProvenanceOntology::validate().unwrap();
    }
}
