// DOLCE classifications for every domain ontology in praxis.
//
// Each domain declares what type of Being it models, per DOLCE upper ontology.
// Reference: Masolo et al., WonderWeb Deliverable D18 (2003)
//
// The Classified trait lives in pr4xis::ontology::upper::classify.
// These impls apply it to domain categories.
//
// NOTE: ontologies that declare `being:` inside `define_ontology!` get their
// Classified impl generated by the macro. Do NOT add manual impls for those.
// Manual impls below are ONLY for ontologies that use `define_category!` or
// `define_dense_category!`, which do not support the `being:` clause.

use pr4xis::ontology::upper::being::Being;
use pr4xis::ontology::upper::classify::Classified;

// =============================================================================
// Cognitive — Cognition (define_category!)
// =============================================================================

impl Classified for crate::cognitive::cognition::distinction::DistinctionCategory {
    fn being() -> Being {
        Being::AbstractObject
    }
    fn classification_reason() -> &'static str {
        "distinction is the most fundamental abstract operation (Laws of Form)"
    }
}

impl Classified for crate::cognitive::cognition::epistemics::EpistemicCategory {
    fn being() -> Being {
        Being::MentalObject
    }
    fn classification_reason() -> &'static str {
        "epistemic states are cognitive/mental (what we know about knowing)"
    }
}

impl Classified for crate::cognitive::cognition::metacognition::MetaCognitionCategory {
    fn being() -> Being {
        Being::MentalObject
    }
    fn classification_reason() -> &'static str {
        "metacognition is a mental process (second-order cybernetics)"
    }
}

impl Classified for crate::cognitive::cognition::self_model::SelfModelCategory {
    fn being() -> Being {
        Being::MentalObject
    }
    fn classification_reason() -> &'static str {
        "self-model is the system's eigenform (von Foerster 1981; IEEE AuR 2021; MAPE-K 2003)"
    }
}

// =============================================================================
// Cognitive — Linguistics (define_category! / define_dense_category!)
// =============================================================================

impl Classified for crate::cognitive::linguistics::lexicon::ontology::LexicalCategory {
    fn being() -> Being {
        Being::SocialObject
    }
    fn classification_reason() -> &'static str {
        "language categories are evolved social conventions"
    }
}

impl Classified for crate::cognitive::linguistics::morphology::tense::TenseCategory {
    fn being() -> Being {
        Being::AbstractObject
    }
    fn classification_reason() -> &'static str {
        "tense/aspect are abstract temporal relations (Reichenbach 1947)"
    }
}

impl Classified for crate::cognitive::linguistics::orthography::distance::SpellingErrorCategory {
    fn being() -> Being {
        Being::Quality
    }
    fn classification_reason() -> &'static str {
        "spelling errors are measurable deviations in written language quality"
    }
}

impl Classified for crate::cognitive::linguistics::orthography::channel::ChannelCategory {
    fn being() -> Being {
        Being::AbstractObject
    }
    fn classification_reason() -> &'static str {
        "the noisy channel is an abstract model (Shannon 1948; Kernighan 1990)"
    }
}

impl Classified for crate::cognitive::linguistics::pragmatics::reference::ReferenceCategory {
    fn being() -> Being {
        Being::AbstractObject
    }
    fn classification_reason() -> &'static str {
        "discourse reference is an abstract framework (Kamp DRT 1981; Centering 1995)"
    }
}

impl Classified for crate::cognitive::linguistics::pragmatics::generation::ProductionCategory {
    fn being() -> Being {
        Being::Process
    }
    fn classification_reason() -> &'static str {
        "language production is a temporal generation process (Levelt 1989)"
    }
}

impl Classified for crate::cognitive::linguistics::pragmatics::nlg::NlgCategory {
    fn being() -> Being {
        Being::AbstractObject
    }
    fn classification_reason() -> &'static str {
        "NLG pipeline is abstract framework (Reiter & Dale 2000)"
    }
}

impl Classified for crate::cognitive::linguistics::pragmatics::response::ResponseCategory {
    fn being() -> Being {
        Being::Process
    }
    fn classification_reason() -> &'static str {
        "response planning is a temporal process (speech act to realization)"
    }
}

// =============================================================================
// Formal — Systems — Control (define_category!)
// =============================================================================

impl Classified for crate::formal::systems::control::ControlCategory {
    fn being() -> Being {
        Being::AbstractObject
    }
    fn classification_reason() -> &'static str {
        "control systems are abstract models of regulation (Wiener 1948; Conant-Ashby 1970)"
    }
}

// =============================================================================
// Applied — HMI — Theming (manual Category impl, no macro)
// =============================================================================

impl Classified for crate::applied::hmi::theming::ontology::ThemingCategory {
    fn being() -> Being {
        Being::Quality
    }
    fn classification_reason() -> &'static str {
        "theming is visual quality specification (base16, color palettes)"
    }
}

// =============================================================================
// Applied — Hardware — Traffic (define_dense_category!)
// =============================================================================

impl Classified for crate::applied::hardware::traffic::ontology::TrafficCategory {
    fn being() -> Being {
        Being::SocialObject
    }
    fn classification_reason() -> &'static str {
        "traffic rules are engineered social conventions"
    }
}

// =============================================================================
// Applied — Hardware — Elevator (manual Category impl, no macro)
// =============================================================================

impl Classified for crate::applied::hardware::elevator::ontology::ElevatorCategory {
    fn being() -> Being {
        Being::SocialObject
    }
    fn classification_reason() -> &'static str {
        "elevator operation rules are engineered specifications"
    }
}

// =============================================================================
// Social — Games — Chess (manual Category impl)
// =============================================================================

impl Classified for crate::social::games::chess::ontology::ChessCategory {
    fn being() -> Being {
        Being::SocialObject
    }
    fn classification_reason() -> &'static str {
        "chess rules are agreed-upon social conventions"
    }
}

// =============================================================================
// Social — Judicial (manual Category impl)
// =============================================================================

impl Classified for crate::social::judicial::ontology::CaseLifecycleCategory {
    fn being() -> Being {
        Being::Process
    }
    fn classification_reason() -> &'static str {
        "a court case is a social process unfolding over time"
    }
}

// =============================================================================
// Social — Software — Markup (manual Category impls)
// =============================================================================

impl Classified for crate::social::software::markup::ontology::MarkupCategory {
    fn being() -> Being {
        Being::SocialObject
    }
    fn classification_reason() -> &'static str {
        "markup languages are social conventions for document structure"
    }
}

impl Classified for crate::social::software::markup::xml::ontology::XmlCategory {
    fn being() -> Being {
        Being::SocialObject
    }
    fn classification_reason() -> &'static str {
        "XML is a W3C standard — an agreed-upon markup language"
    }
}

impl Classified for crate::social::software::markup::xml::rdf::ontology::RdfCategory {
    fn being() -> Being {
        Being::SocialObject
    }
    fn classification_reason() -> &'static str {
        "RDF is a W3C standard — an agreed-upon data model"
    }
}

impl Classified for crate::social::software::markup::xml::owl::ontology::OwlCategory {
    fn being() -> Being {
        Being::SocialObject
    }
    fn classification_reason() -> &'static str {
        "OWL is a W3C standard — an agreed-upon ontology language"
    }
}
