// DOLCE classifications for every domain ontology in praxis.
//
// Each domain declares what type of Being it models, per DOLCE upper ontology.
// Reference: Masolo et al., WonderWeb Deliverable D18 (2003)
//
// The Classified trait lives in pr4xis::ontology::upper::classify.
// These impls apply it to domain categories.
//
// NOTE: ontologies that declare `being:` inside `define_ontology!` get their
// Classified impl generated by the macro. Do NOT add manual impls for those.
// Currently auto-classified: ArtifactIdentityCategory, StagingCategory,
// DataProvisioningCategory.

use pr4xis::ontology::upper::being::Being;
use pr4xis::ontology::upper::classify::Classified;

// =============================================================================
// Cognitive — Cognition
// =============================================================================

impl Classified for crate::cognitive::cognition::distinction::DistinctionCategory {
    fn being() -> Being {
        Being::AbstractObject
    }
    fn classification_reason() -> &'static str {
        "distinction is the most fundamental abstract operation (Laws of Form)"
    }
}

impl Classified for crate::cognitive::cognition::epistemics::EpistemicCategory {
    fn being() -> Being {
        Being::MentalObject
    }
    fn classification_reason() -> &'static str {
        "epistemic states are cognitive/mental (what we know about knowing)"
    }
}

impl Classified for crate::cognitive::cognition::metacognition::MetaCognitionCategory {
    fn being() -> Being {
        Being::MentalObject
    }
    fn classification_reason() -> &'static str {
        "metacognition is a mental process (second-order cybernetics)"
    }
}

impl Classified for crate::cognitive::cognition::self_model::SelfModelCategory {
    fn being() -> Being {
        Being::MentalObject
    }
    fn classification_reason() -> &'static str {
        "self-model is the system's eigenform (von Foerster 1981; IEEE AuR 2021; MAPE-K 2003)"
    }
}

// =============================================================================
// Cognitive — Linguistics
// =============================================================================

impl Classified for crate::cognitive::linguistics::lexicon::ontology::LexicalCategory {
    fn being() -> Being {
        Being::SocialObject
    }
    fn classification_reason() -> &'static str {
        "language categories are evolved social conventions"
    }
}

impl Classified for crate::cognitive::linguistics::morphology::tense::TenseCategory {
    fn being() -> Being {
        Being::AbstractObject
    }
    fn classification_reason() -> &'static str {
        "tense/aspect are abstract temporal relations (Reichenbach 1947)"
    }
}

impl Classified for crate::cognitive::linguistics::orthography::distance::SpellingErrorCategory {
    fn being() -> Being {
        Being::Quality
    }
    fn classification_reason() -> &'static str {
        "spelling errors are measurable deviations in written language quality"
    }
}

impl Classified for crate::cognitive::linguistics::orthography::channel::ChannelCategory {
    fn being() -> Being {
        Being::AbstractObject
    }
    fn classification_reason() -> &'static str {
        "the noisy channel is an abstract model (Shannon 1948; Kernighan 1990)"
    }
}

impl Classified for crate::cognitive::linguistics::pragmatics::reference::ReferenceCategory {
    fn being() -> Being {
        Being::AbstractObject
    }
    fn classification_reason() -> &'static str {
        "discourse reference is an abstract framework (Kamp DRT 1981; Centering 1995)"
    }
}

impl Classified for crate::cognitive::linguistics::pragmatics::generation::ProductionCategory {
    fn being() -> Being {
        Being::Process
    }
    fn classification_reason() -> &'static str {
        "language production is a temporal generation process (Levelt 1989)"
    }
}

impl Classified for crate::cognitive::linguistics::pragmatics::nlg::NlgCategory {
    fn being() -> Being {
        Being::AbstractObject
    }
    fn classification_reason() -> &'static str {
        "NLG pipeline is abstract framework (Reiter & Dale 2000)"
    }
}

impl Classified for crate::cognitive::linguistics::pragmatics::response::ResponseCategory {
    fn being() -> Being {
        Being::Process
    }
    fn classification_reason() -> &'static str {
        "response planning is a temporal process (speech act to realization)"
    }
}

// =============================================================================
// Formal — Mathematics
// =============================================================================

impl Classified for crate::formal::math::ontology::NumberHierarchy {
    fn being() -> Being {
        Being::AbstractObject
    }
    fn classification_reason() -> &'static str {
        "numbers and mathematical structures are timeless abstracts"
    }
}

impl Classified for crate::formal::math::geometry::ontology::GeometryCategory {
    fn being() -> Being {
        Being::AbstractObject
    }
    fn classification_reason() -> &'static str {
        "geometry is a timeless mathematical structure (Hilbert)"
    }
}

impl Classified for crate::formal::math::linear_algebra::ontology::LinearAlgebraCategory {
    fn being() -> Being {
        Being::AbstractObject
    }
    fn classification_reason() -> &'static str {
        "linear algebra is abstract mathematical structure"
    }
}

impl Classified for crate::formal::math::probability::ontology::ProbabilityCategory {
    fn being() -> Being {
        Being::AbstractObject
    }
    fn classification_reason() -> &'static str {
        "probability theory is abstract (Kolmogorov 1933)"
    }
}

impl Classified for crate::formal::math::quantity::ontology::DimensionCategory {
    fn being() -> Being {
        Being::AbstractObject
    }
    fn classification_reason() -> &'static str {
        "dimensional analysis is abstract (SI system)"
    }
}

impl Classified for crate::formal::math::rotation::ontology::RotationCategory {
    fn being() -> Being {
        Being::AbstractObject
    }
    fn classification_reason() -> &'static str {
        "rotation representations are abstract mathematical objects"
    }
}

impl Classified for crate::formal::math::signal_processing::ontology::SignalCategory {
    fn being() -> Being {
        Being::AbstractObject
    }
    fn classification_reason() -> &'static str {
        "signal processing is abstract mathematical framework"
    }
}

impl Classified for crate::formal::math::statistics::ontology::StatisticalCategory {
    fn being() -> Being {
        Being::AbstractObject
    }
    fn classification_reason() -> &'static str {
        "statistics is abstract mathematical framework"
    }
}

impl Classified for crate::formal::math::temporal::ontology::TimeSystemCategory {
    fn being() -> Being {
        Being::AbstractObject
    }
    fn classification_reason() -> &'static str {
        "time systems are abstract reference frameworks (UTC, TAI, GPS time)"
    }
}

impl Classified for crate::formal::math::control_theory::ontology::ControlCategory {
    fn being() -> Being {
        Being::AbstractObject
    }
    fn classification_reason() -> &'static str {
        "control theory is abstract mathematical framework (Kalman 1960)"
    }
}

// =============================================================================
// Formal — Meta
// =============================================================================

// ArtifactIdentityCategory: auto-classified via `being: AbstractObject` in define_ontology!
// StagingCategory: auto-classified via `being: AbstractObject` in define_ontology!

impl Classified for crate::formal::meta::ontology_diagnostics::ontology::MetaCategory {
    fn being() -> Being {
        Being::AbstractObject
    }
    fn classification_reason() -> &'static str {
        "meta-ontology engineering is abstract (ontology of ontologies)"
    }
}

// =============================================================================
// Formal — Information
// =============================================================================

impl Classified for crate::formal::information::ontology::InfoCategory {
    fn being() -> Being {
        Being::AbstractObject
    }
    fn classification_reason() -> &'static str {
        "information is an abstract quantity (bits, entropy)"
    }
}

impl Classified for crate::formal::information::communication::ontology::CommunicationCategory {
    fn being() -> Being {
        Being::AbstractObject
    }
    fn classification_reason() -> &'static str {
        "communication is an abstract framework (Shannon 1948; Jakobson 1960)"
    }
}

impl Classified for crate::formal::information::dialogue::ontology::DialogueCategory {
    fn being() -> Being {
        Being::Process
    }
    fn classification_reason() -> &'static str {
        "dialogue is an extended temporal process between participants"
    }
}

impl Classified for crate::formal::information::events::ontology::EventCategory {
    fn being() -> Being {
        Being::AbstractObject
    }
    fn classification_reason() -> &'static str {
        "event-driven architecture is an abstract pattern"
    }
}

impl Classified for crate::formal::information::concurrency::ontology::ConcurrencyCategory {
    fn being() -> Being {
        Being::AbstractObject
    }
    fn classification_reason() -> &'static str {
        "concurrency is an abstract model (CSP, CCS, Actor)"
    }
}

impl Classified for crate::formal::information::provenance::ontology::ProvenanceCategory {
    fn being() -> Being {
        Being::AbstractObject
    }
    fn classification_reason() -> &'static str {
        "provenance is an abstract framework for tracking knowledge origins (W3C PROV-O)"
    }
}

impl Classified for crate::formal::information::knowledge::ontology::KnowledgeBaseCategory {
    fn being() -> Being {
        Being::AbstractObject
    }
    fn classification_reason() -> &'static str {
        "knowledge base is an abstract self-describing framework (VoID 2011; Herre & Loebe 2005)"
    }
}

impl Classified for crate::formal::information::diagnostics::ontology::DiagnosticCategory {
    fn being() -> Being {
        Being::AbstractObject
    }
    fn classification_reason() -> &'static str {
        "diagnostics is abstract cycle: observation, hypothesis, test, conclusion (Reiter 1987)"
    }
}

impl Classified for crate::formal::information::measurement::ontology::MeasurementCategory {
    fn being() -> Being {
        Being::Quality
    }
    fn classification_reason() -> &'static str {
        "measurement is a quality-bearing framework (ISO GUM, VIM)"
    }
}

impl Classified for crate::formal::information::schema::ontology::SchemaCategory {
    fn being() -> Being {
        Being::AbstractObject
    }
    fn classification_reason() -> &'static str {
        "schema is abstract structural framework (Spivak 2012 functorial data migration)"
    }
}

impl Classified for crate::formal::information::storage::ontology::RepositoryCategory {
    fn being() -> Being {
        Being::AbstractObject
    }
    fn classification_reason() -> &'static str {
        "repository/store is abstract persistence framework (Haerder & Reuter 1983 ACID)"
    }
}

// =============================================================================
// Formal — Systems
// =============================================================================

impl Classified for crate::formal::systems::ontology::SystemsCategory {
    fn being() -> Being {
        Being::AbstractObject
    }
    fn classification_reason() -> &'static str {
        "systems theory is an abstract framework (cybernetics)"
    }
}

impl Classified for crate::formal::systems::control::ControlCategory {
    fn being() -> Being {
        Being::AbstractObject
    }
    fn classification_reason() -> &'static str {
        "control systems are abstract models of regulation (Wiener 1948; Conant-Ashby 1970)"
    }
}

// =============================================================================
// Formal — Other (analytical, derivation, optimization, recommendation)
// =============================================================================

impl Classified for crate::formal::analytical_methods::ontology::AnalyticalCategory {
    fn being() -> Being {
        Being::AbstractObject
    }
    fn classification_reason() -> &'static str {
        "structural analysis methods are abstract mathematical tools"
    }
}

impl Classified for crate::formal::derivation::ontology::DerivationCategory {
    fn being() -> Being {
        Being::AbstractObject
    }
    fn classification_reason() -> &'static str {
        "logical derivation is abstract proof construction"
    }
}

impl Classified for crate::formal::optimization::ontology::OptimizationCategory {
    fn being() -> Being {
        Being::AbstractObject
    }
    fn classification_reason() -> &'static str {
        "optimization methods are abstract mathematical techniques"
    }
}

impl Classified for crate::formal::recommendation::ontology::RecommendationCategory {
    fn being() -> Being {
        Being::AbstractObject
    }
    fn classification_reason() -> &'static str {
        "recommendation/decision-making is abstract framework"
    }
}

// =============================================================================
// Applied — Data Provisioning
// =============================================================================

// DataProvisioningCategory: auto-classified via `being: Process` in define_ontology!

// =============================================================================
// Applied — HMI
// =============================================================================

impl Classified for crate::applied::hmi::theming::ontology::ThemingCategory {
    fn being() -> Being {
        Being::Quality
    }
    fn classification_reason() -> &'static str {
        "theming is visual quality specification (base16, color palettes)"
    }
}

// =============================================================================
// Applied — Navigation
// =============================================================================

impl Classified for crate::applied::navigation::ahrs::ontology::AhrsCategory {
    fn being() -> Being {
        Being::Process
    }
    fn classification_reason() -> &'static str {
        "AHRS is a continuous estimation process (Madgwick, Mahony filters)"
    }
}

impl Classified for crate::applied::navigation::celestial::ontology::CelestialCategory {
    fn being() -> Being {
        Being::Process
    }
    fn classification_reason() -> &'static str {
        "celestial navigation is a measurement-to-position process"
    }
}

impl Classified for crate::applied::navigation::gnss::ontology::GnssCategory {
    fn being() -> Being {
        Being::Process
    }
    fn classification_reason() -> &'static str {
        "GNSS positioning is a continuous satellite-ranging process"
    }
}

impl Classified for crate::applied::navigation::imu::ontology::ImuCategory {
    fn being() -> Being {
        Being::PhysicalEndurant
    }
    fn classification_reason() -> &'static str {
        "IMU models physical inertial sensors (accelerometers, gyroscopes)"
    }
}

impl Classified for crate::applied::navigation::ins_gnss::ontology::InsGnssCategory {
    fn being() -> Being {
        Being::Process
    }
    fn classification_reason() -> &'static str {
        "INS/GNSS coupling is a sensor fusion process"
    }
}

impl Classified for crate::applied::navigation::odometry::ontology::OdometryCategory {
    fn being() -> Being {
        Being::Process
    }
    fn classification_reason() -> &'static str {
        "odometry is dead-reckoning estimation process"
    }
}

// =============================================================================
// Applied — Sensor Fusion
// =============================================================================

impl Classified for crate::applied::sensor_fusion::fusion::ontology::FusionCategory {
    fn being() -> Being {
        Being::Process
    }
    fn classification_reason() -> &'static str {
        "sensor fusion is a continuous estimation process (Kalman 1960)"
    }
}

impl Classified for crate::applied::sensor_fusion::observation::ontology::ObservationCategory {
    fn being() -> Being {
        Being::Event
    }
    fn classification_reason() -> &'static str {
        "an observation is a discrete measurement event"
    }
}

impl Classified for crate::applied::sensor_fusion::sensor::ontology::SensorCategory {
    fn being() -> Being {
        Being::PhysicalEndurant
    }
    fn classification_reason() -> &'static str {
        "sensors are physical measurement devices"
    }
}

impl Classified for crate::applied::sensor_fusion::state::ontology::EstimationCategory {
    fn being() -> Being {
        Being::AbstractObject
    }
    fn classification_reason() -> &'static str {
        "state estimation is abstract framework (Bayesian inference)"
    }
}

impl Classified for crate::applied::sensor_fusion::time::ontology::SensorTimeCategory {
    fn being() -> Being {
        Being::AbstractObject
    }
    fn classification_reason() -> &'static str {
        "time synchronization strategies are abstract protocols"
    }
}

// =============================================================================
// Applied — Space
// =============================================================================

impl Classified for crate::applied::space::attitude::ontology::AttitudeCategory {
    fn being() -> Being {
        Being::Process
    }
    fn classification_reason() -> &'static str {
        "attitude determination is a continuous estimation process"
    }
}

impl Classified for crate::applied::space::orbit::ontology::OrbitCategory {
    fn being() -> Being {
        Being::Process
    }
    fn classification_reason() -> &'static str {
        "orbit determination is a continuous estimation process (Kepler, SGP4)"
    }
}

// =============================================================================
// Applied — Tracking
// =============================================================================

impl Classified for crate::applied::tracking::single_target::ontology::TargetStateCategory {
    fn being() -> Being {
        Being::Process
    }
    fn classification_reason() -> &'static str {
        "target tracking is a continuous state estimation process"
    }
}

// =============================================================================
// Applied — Underwater
// =============================================================================

impl Classified for crate::applied::underwater::acoustic::ontology::AcousticCategory {
    fn being() -> Being {
        Being::PhysicalEndurant
    }
    fn classification_reason() -> &'static str {
        "underwater acoustic systems are physical sonar hardware"
    }
}

impl Classified for crate::applied::underwater::auv::ontology::AuvCategory {
    fn being() -> Being {
        Being::PhysicalEndurant
    }
    fn classification_reason() -> &'static str {
        "autonomous underwater vehicles are physical platforms"
    }
}

// =============================================================================
// Applied — Industrial
// =============================================================================

impl Classified for crate::applied::industrial::process::ontology::ProcessCategory {
    fn being() -> Being {
        Being::Process
    }
    fn classification_reason() -> &'static str {
        "industrial process control is a continuous regulation process"
    }
}

impl Classified for crate::applied::industrial::structural::ontology::StructuralCategory {
    fn being() -> Being {
        Being::PhysicalEndurant
    }
    fn classification_reason() -> &'static str {
        "structural health monitoring covers physical infrastructure"
    }
}

// =============================================================================
// Applied — Localization
// =============================================================================

impl Classified for crate::applied::localization::terrain::ontology::TerrainCategory {
    fn being() -> Being {
        Being::PhysicalEndurant
    }
    fn classification_reason() -> &'static str {
        "terrain features are physical geographic entities"
    }
}

// =============================================================================
// Applied — Perception
// =============================================================================

impl Classified for crate::applied::perception::occupancy::ontology::OccupancyCategory {
    fn being() -> Being {
        Being::Process
    }
    fn classification_reason() -> &'static str {
        "occupancy grid mapping is a continuous spatial inference process"
    }
}

// =============================================================================
// Applied — Hardware
// =============================================================================

impl Classified for crate::applied::hardware::traffic::ontology::TrafficCategory {
    fn being() -> Being {
        Being::SocialObject
    }
    fn classification_reason() -> &'static str {
        "traffic rules are engineered social conventions"
    }
}

impl Classified for crate::applied::hardware::elevator::ontology::ElevatorCategory {
    fn being() -> Being {
        Being::SocialObject
    }
    fn classification_reason() -> &'static str {
        "elevator operation rules are engineered specifications"
    }
}

// =============================================================================
// Natural — Physics
// =============================================================================

impl Classified for crate::natural::physics::ontology::PhysicsCategory {
    fn being() -> Being {
        Being::AbstractObject
    }
    fn classification_reason() -> &'static str {
        "physical laws are timeless mathematical relations"
    }
}

impl Classified for crate::natural::physics::kinematics::ontology::KinematicsCategory {
    fn being() -> Being {
        Being::AbstractObject
    }
    fn classification_reason() -> &'static str {
        "kinematics is abstract motion description (position, velocity, acceleration)"
    }
}

// =============================================================================
// Natural — Geodesy
// =============================================================================

impl Classified for crate::natural::geodesy::ontology::GeodesyCategory {
    fn being() -> Being {
        Being::AbstractObject
    }
    fn classification_reason() -> &'static str {
        "geodesy is abstract framework for coordinate reference systems (WGS84, ECEF)"
    }
}

// =============================================================================
// Natural — Colors
// =============================================================================

impl Classified for crate::natural::colors::ontology::ColorCategory {
    fn being() -> Being {
        Being::Quality
    }
    fn classification_reason() -> &'static str {
        "color is a measurable perceptual quality"
    }
}

// =============================================================================
// Natural — Biomedical
// =============================================================================

impl Classified for crate::natural::biomedical::acoustics::ontology::AcousticsCategory {
    fn being() -> Being {
        Being::Quality
    }
    fn classification_reason() -> &'static str {
        "acoustics models measurable sound properties"
    }
}

impl Classified for crate::natural::biomedical::biochemistry::ontology::BiochemistryCategory {
    fn being() -> Being {
        Being::AbstractObject
    }
    fn classification_reason() -> &'static str {
        "biochemistry is abstract molecular interaction framework"
    }
}

impl Classified for crate::natural::biomedical::bioelectricity::ontology::BioelectricCategory {
    fn being() -> Being {
        Being::AbstractObject
    }
    fn classification_reason() -> &'static str {
        "bioelectricity is abstract framework for bioelectric signaling (Levin 2012)"
    }
}

impl Classified for crate::natural::biomedical::bioelectricity::morphospace::MorphospaceCategory {
    fn being() -> Being {
        Being::AbstractObject
    }
    fn classification_reason() -> &'static str {
        "morphospace is abstract state space of possible anatomies (Levin 2019)"
    }
}

impl Classified for crate::natural::biomedical::biology::ontology::BiologyCategory {
    fn being() -> Being {
        Being::AbstractObject
    }
    fn classification_reason() -> &'static str {
        "biological organization is abstract hierarchy (cell, tissue, organ, organism)"
    }
}

impl Classified for crate::natural::biomedical::biophysics::ontology::BiophysicsCategory {
    fn being() -> Being {
        Being::Quality
    }
    fn classification_reason() -> &'static str {
        "biophysics models measurable physical properties of living systems"
    }
}

impl Classified for crate::natural::biomedical::chemistry::ontology::ChemistryCategory {
    fn being() -> Being {
        Being::AbstractObject
    }
    fn classification_reason() -> &'static str {
        "chemistry is abstract framework for matter and reactions (periodic table)"
    }
}

impl Classified
    for crate::natural::biomedical::electrophysiology::ontology::ElectrophysiologyCategory
{
    fn being() -> Being {
        Being::Quality
    }
    fn classification_reason() -> &'static str {
        "electrophysiology models measurable bioelectric signals (EEG, ECG, patch clamp)"
    }
}

impl Classified for crate::natural::biomedical::hematology::ontology::HematologyCategory {
    fn being() -> Being {
        Being::AbstractObject
    }
    fn classification_reason() -> &'static str {
        "hematology is abstract classification of blood components"
    }
}

impl Classified for crate::natural::biomedical::immunology::ontology::ImmunologyCategory {
    fn being() -> Being {
        Being::AbstractObject
    }
    fn classification_reason() -> &'static str {
        "immunology is abstract framework for immune response (innate, adaptive)"
    }
}

impl Classified for crate::natural::biomedical::mechanobiology::ontology::MechanobiologyCategory {
    fn being() -> Being {
        Being::Quality
    }
    fn classification_reason() -> &'static str {
        "mechanobiology models measurable mechanical forces in living systems"
    }
}

impl Classified for crate::natural::biomedical::molecular::ontology::MolecularCategory {
    fn being() -> Being {
        Being::AbstractObject
    }
    fn classification_reason() -> &'static str {
        "molecular biology is abstract framework (DNA, RNA, protein)"
    }
}

impl Classified for crate::natural::biomedical::pathology::ontology::PathologyCategory {
    fn being() -> Being {
        Being::AbstractObject
    }
    fn classification_reason() -> &'static str {
        "pathology is abstract disease classification (ICD)"
    }
}

impl Classified for crate::natural::biomedical::pharmacology::ontology::PharmacologyCategory {
    fn being() -> Being {
        Being::Process
    }
    fn classification_reason() -> &'static str {
        "pharmacology models drug action as temporal process (pharmacokinetics, pharmacodynamics)"
    }
}

impl Classified for crate::natural::biomedical::regeneration::ontology::RegenerationCategory {
    fn being() -> Being {
        Being::Process
    }
    fn classification_reason() -> &'static str {
        "regeneration is a temporal biological process (Levin 2012)"
    }
}

// =============================================================================
// Natural — Hearing
// =============================================================================

impl Classified for crate::natural::hearing::acoustics::ontology::AcousticsCategory {
    fn being() -> Being {
        Being::Quality
    }
    fn classification_reason() -> &'static str {
        "hearing acoustics models measurable sound properties"
    }
}

impl Classified for crate::natural::hearing::anatomy::ontology::AnatomyCategory {
    fn being() -> Being {
        Being::PhysicalEndurant
    }
    fn classification_reason() -> &'static str {
        "auditory anatomy models physical structures (cochlea, ossicles)"
    }
}

impl Classified for crate::natural::hearing::audiology::ontology::AudiologyCategory {
    fn being() -> Being {
        Being::Process
    }
    fn classification_reason() -> &'static str {
        "audiology is clinical assessment process (audiometry, diagnostics)"
    }
}

impl Classified for crate::natural::hearing::auditory_neuroscience::ontology::NeuroscienceCategory {
    fn being() -> Being {
        Being::AbstractObject
    }
    fn classification_reason() -> &'static str {
        "auditory neuroscience is abstract neural coding framework"
    }
}

impl Classified for crate::natural::hearing::bone_conduction::ontology::BoneConductionCategory {
    fn being() -> Being {
        Being::PhysicalEndurant
    }
    fn classification_reason() -> &'static str {
        "bone conduction models physical vibration pathways through skull"
    }
}

impl Classified for crate::natural::hearing::devices::ontology::DeviceCategory {
    fn being() -> Being {
        Being::PhysicalEndurant
    }
    fn classification_reason() -> &'static str {
        "hearing devices are physical artifacts (hearing aids, cochlear implants)"
    }
}

impl Classified
    for crate::natural::hearing::environmental_acoustics::ontology::EnvironmentalAcousticsCategory
{
    fn being() -> Being {
        Being::Quality
    }
    fn classification_reason() -> &'static str {
        "environmental acoustics models measurable room/space properties (RT60, absorption)"
    }
}

impl Classified for crate::natural::hearing::music_perception::ontology::MusicPerceptionCategory {
    fn being() -> Being {
        Being::MentalObject
    }
    fn classification_reason() -> &'static str {
        "music perception is cognitive processing of auditory input"
    }
}

impl Classified for crate::natural::hearing::pathology::ontology::PathologyCategory {
    fn being() -> Being {
        Being::AbstractObject
    }
    fn classification_reason() -> &'static str {
        "hearing pathology is abstract classification of hearing disorders"
    }
}

impl Classified for crate::natural::hearing::psychoacoustics::ontology::PsychoacousticsCategory {
    fn being() -> Being {
        Being::MentalObject
    }
    fn classification_reason() -> &'static str {
        "psychoacoustics is perceptual/mental response to sound (loudness, pitch, masking)"
    }
}

impl Classified for crate::natural::hearing::signal_processing::ontology::SignalProcessingCategory {
    fn being() -> Being {
        Being::AbstractObject
    }
    fn classification_reason() -> &'static str {
        "hearing signal processing is abstract framework (filters, FFT, noise reduction)"
    }
}

impl Classified for crate::natural::hearing::speech::ontology::SpeechCategory {
    fn being() -> Being {
        Being::Process
    }
    fn classification_reason() -> &'static str {
        "speech is a temporal production/perception process"
    }
}

impl Classified for crate::natural::hearing::transduction::ontology::TransductionCategory {
    fn being() -> Being {
        Being::Process
    }
    fn classification_reason() -> &'static str {
        "mechanotransduction is physical-to-electrical conversion process in hair cells"
    }
}

impl Classified for crate::natural::hearing::vestibular::ontology::VestibularCategory {
    fn being() -> Being {
        Being::PhysicalEndurant
    }
    fn classification_reason() -> &'static str {
        "vestibular system is physical balance apparatus (semicircular canals, otoliths)"
    }
}

// =============================================================================
// Social — Games
// =============================================================================

impl Classified for crate::social::games::chess::ontology::ChessCategory {
    fn being() -> Being {
        Being::SocialObject
    }
    fn classification_reason() -> &'static str {
        "chess rules are agreed-upon social conventions"
    }
}

impl Classified for crate::social::games::rubik::ontology::RubikCategory {
    fn being() -> Being {
        Being::SocialObject
    }
    fn classification_reason() -> &'static str {
        "puzzle rules are engineered social constructs"
    }
}

// =============================================================================
// Social — Judicial
// =============================================================================

impl Classified for crate::social::judicial::ontology::CaseLifecycleCategory {
    fn being() -> Being {
        Being::Process
    }
    fn classification_reason() -> &'static str {
        "a court case is a social process unfolding over time"
    }
}

// =============================================================================
// Social — Military
// =============================================================================

impl Classified for crate::social::military::electronic_warfare::ontology::EwCategory {
    fn being() -> Being {
        Being::SocialObject
    }
    fn classification_reason() -> &'static str {
        "electronic warfare doctrine is an agreed-upon social framework"
    }
}

// =============================================================================
// Social — Software
// =============================================================================

impl Classified for crate::social::software::protocols::http::ontology::HttpMethodCategory {
    fn being() -> Being {
        Being::SocialObject
    }
    fn classification_reason() -> &'static str {
        "HTTP is a W3C/IETF standard — an agreed-upon protocol"
    }
}

impl Classified for crate::social::software::markup::ontology::MarkupCategory {
    fn being() -> Being {
        Being::SocialObject
    }
    fn classification_reason() -> &'static str {
        "markup languages are social conventions for document structure"
    }
}

impl Classified for crate::social::software::markup::xml::ontology::XmlCategory {
    fn being() -> Being {
        Being::SocialObject
    }
    fn classification_reason() -> &'static str {
        "XML is a W3C standard — an agreed-upon markup language"
    }
}

impl Classified for crate::social::software::markup::xml::rdf::ontology::RdfCategory {
    fn being() -> Being {
        Being::SocialObject
    }
    fn classification_reason() -> &'static str {
        "RDF is a W3C standard — an agreed-upon data model"
    }
}

impl Classified for crate::social::software::markup::xml::owl::ontology::OwlCategory {
    fn being() -> Being {
        Being::SocialObject
    }
    fn classification_reason() -> &'static str {
        "OWL is a W3C standard — an agreed-upon ontology language"
    }
}
