//! Tests for the staging ontology — category laws, taxonomy, causation,
//! domain axioms, and property-based tests over the staging level quality.

#[allow(unused_imports)]
use alloc::{boxed::Box, format, string::String, string::ToString, vec, vec::Vec};

use super::ontology::{
    EachProjectionRaisesStagingByOne, EveryProgramKindIsAProgram, FutamuraCausalGraph,
    FutamuraChainIsComplete, FutamuraStep, StageConcept, StagingCategory, StagingLevel,
    StagingOntology, StagingTaxonomy, Temporality, TemporalityTag,
};
use pr4xis::category::Concept;
use pr4xis::ontology::reasoning::{causation, taxonomy};
use pr4xis::ontology::{Axiom, Ontology, Quality};
use proptest::prelude::*;

// =============================================================================
// Category laws (auto-generated by define_ontology!)
// =============================================================================

#[test]
fn category_laws() {
    pr4xis::category::validate::check_category_laws::<StagingCategory>().unwrap();
}

#[test]
fn ontology_validates() {
    StagingOntology::validate().unwrap();
}

// =============================================================================
// Entity surface
// =============================================================================

#[test]
fn ten_stage_concepts() {
    // The ontology has 10 stage concepts: Program, Interpreter, Compiler,
    // Specializer, CompilerGenerator, SourceProgram, ObjectProgram,
    // ResidualProgram, StaticInput, DynamicInput.
    assert_eq!(StageConcept::variants().len(), 10);
}

#[test]
fn five_futamura_steps() {
    // Write, Specialize, Produce, GenerateCompiler, GenerateCogen.
    assert_eq!(FutamuraStep::variants().len(), 5);
}

// =============================================================================
// Taxonomy: every program-kind is-a Program
// =============================================================================

#[test]
fn interpreter_is_a_program() {
    let ancestors = taxonomy::ancestors::<StagingTaxonomy>(&StageConcept::Interpreter);
    assert!(ancestors.contains(&StageConcept::Program));
}

#[test]
fn compiler_is_a_program() {
    let ancestors = taxonomy::ancestors::<StagingTaxonomy>(&StageConcept::Compiler);
    assert!(ancestors.contains(&StageConcept::Program));
}

#[test]
fn specializer_is_a_program() {
    let ancestors = taxonomy::ancestors::<StagingTaxonomy>(&StageConcept::Specializer);
    assert!(ancestors.contains(&StageConcept::Program));
}

#[test]
fn compiler_generator_is_a_program() {
    let ancestors = taxonomy::ancestors::<StagingTaxonomy>(&StageConcept::CompilerGenerator);
    assert!(ancestors.contains(&StageConcept::Program));
}

#[test]
fn source_object_residual_are_programs() {
    for c in [
        StageConcept::SourceProgram,
        StageConcept::ObjectProgram,
        StageConcept::ResidualProgram,
    ] {
        let ancestors = taxonomy::ancestors::<StagingTaxonomy>(&c);
        assert!(
            ancestors.contains(&StageConcept::Program),
            "{:?} is not classified as a Program",
            c
        );
    }
}

// =============================================================================
// Causation: Futamura projection chain
// =============================================================================

#[test]
fn futamura_chain_reaches_cogen() {
    let reach = causation::effects_of::<FutamuraCausalGraph>(&FutamuraStep::WriteInterpreter);
    assert!(reach.contains(&FutamuraStep::ProduceObjectProgram));
    assert!(reach.contains(&FutamuraStep::GenerateCompiler));
    assert!(reach.contains(&FutamuraStep::GenerateCompilerGenerator));
}

#[test]
fn object_program_caused_by_specialization() {
    let causes = causation::causes_of::<FutamuraCausalGraph>(&FutamuraStep::ProduceObjectProgram);
    assert!(causes.contains(&FutamuraStep::SpecializeInterpreter));
}

#[test]
fn compiler_causes_cogen() {
    let causes =
        causation::causes_of::<FutamuraCausalGraph>(&FutamuraStep::GenerateCompilerGenerator);
    assert!(causes.contains(&FutamuraStep::GenerateCompiler));
}

// =============================================================================
// Qualities
// =============================================================================

#[test]
fn static_input_is_static() {
    assert_eq!(
        TemporalityTag.get(&StageConcept::StaticInput),
        Some(Temporality::Static)
    );
}

#[test]
fn dynamic_input_is_dynamic() {
    assert_eq!(
        TemporalityTag.get(&StageConcept::DynamicInput),
        Some(Temporality::Dynamic)
    );
}

#[test]
fn programs_are_mixed_temporality() {
    for c in [
        StageConcept::Program,
        StageConcept::Interpreter,
        StageConcept::Compiler,
        StageConcept::Specializer,
    ] {
        assert_eq!(
            TemporalityTag.get(&c),
            Some(Temporality::Mixed),
            "{:?} should be Mixed temporality",
            c
        );
    }
}

#[test]
fn staging_levels_are_assigned_to_every_concept() {
    for c in StageConcept::variants() {
        assert!(
            StagingLevel.get(&c).is_some(),
            "{:?} missing staging level",
            c
        );
    }
}

#[test]
fn cogen_is_at_staging_level_three() {
    assert_eq!(StagingLevel.get(&StageConcept::CompilerGenerator), Some(3));
}

// =============================================================================
// Domain axioms
// =============================================================================

#[test]
fn axiom_every_program_kind_is_a_program() {
    assert!(EveryProgramKindIsAProgram.holds());
}

#[test]
fn axiom_futamura_chain_is_complete() {
    assert!(FutamuraChainIsComplete.holds());
}

#[test]
fn axiom_each_projection_raises_staging_by_one() {
    assert!(EachProjectionRaisesStagingByOne.holds());
}

#[test]
fn all_domain_axioms_hold() {
    for axiom in StagingOntology::domain_axioms() {
        assert!(
            axiom.holds(),
            "domain axiom does not hold: {}",
            axiom.description()
        );
    }
}

// =============================================================================
// Property-based tests
// =============================================================================

fn arb_stage_concept() -> impl Strategy<Value = StageConcept> {
    prop_oneof![
        Just(StageConcept::Program),
        Just(StageConcept::Interpreter),
        Just(StageConcept::Compiler),
        Just(StageConcept::Specializer),
        Just(StageConcept::CompilerGenerator),
        Just(StageConcept::SourceProgram),
        Just(StageConcept::ObjectProgram),
        Just(StageConcept::ResidualProgram),
        Just(StageConcept::StaticInput),
        Just(StageConcept::DynamicInput),
    ]
}

fn arb_futamura_step() -> impl Strategy<Value = FutamuraStep> {
    prop_oneof![
        Just(FutamuraStep::WriteInterpreter),
        Just(FutamuraStep::SpecializeInterpreter),
        Just(FutamuraStep::ProduceObjectProgram),
        Just(FutamuraStep::GenerateCompiler),
        Just(FutamuraStep::GenerateCompilerGenerator),
    ]
}

/// Generator over the real Futamura ladder transitions as (pre, post,
/// expected_level_delta) triples. Each tuple is a specific projection that
/// should raise the staging level by a known amount.
fn arb_futamura_ladder_pair() -> impl Strategy<Value = (StageConcept, StageConcept, usize)> {
    use StageConcept::*;
    prop_oneof![
        // First Futamura projection: specializing the interpreter yields the object program.
        Just((Interpreter, ObjectProgram, 1)),
        // Second Futamura projection: specializing α wrt the interpreter yields a compiler.
        Just((Interpreter, Compiler, 2)),
        // Third Futamura projection: specializing α wrt α yields the compiler-generator.
        Just((Interpreter, CompilerGenerator, 3)),
        // Second projection from the object program's own perspective: still +1 to reach compiler.
        Just((ObjectProgram, Compiler, 1)),
        // Third projection from compiler's perspective: +1 to reach cogen.
        Just((Compiler, CompilerGenerator, 1)),
    ]
}

proptest! {
    /// Every stage concept has a defined temporality. There are no concepts
    /// outside the static/dynamic/mixed trichotomy.
    #[test]
    fn prop_every_concept_has_temporality(c in arb_stage_concept()) {
        prop_assert!(TemporalityTag.get(&c).is_some());
    }

    /// Every stage concept has a staging level in [0, 3]. Nothing escapes
    /// the Futamura ladder.
    #[test]
    fn prop_staging_level_bounded(c in arb_stage_concept()) {
        let level = StagingLevel.get(&c).unwrap();
        prop_assert!(level <= 3, "level out of bounds for {:?}: {}", c, level);
    }

    /// Each Futamura projection along the ladder raises the staging level by
    /// exactly the expected delta. The generator picks a (pre, post) pair
    /// from the set of real Futamura transitions; for every such pair the
    /// assertion is exact (=), not a bound (≤).
    ///
    /// This is the proptest form of the `EachProjectionRaisesStagingByOne`
    /// domain axiom, extended to the full ladder depth.
    #[test]
    fn prop_futamura_ladder_deltas_are_exact(pair in arb_futamura_ladder_pair()) {
        let (pre, post, expected_delta) = pair;
        let pre_level = StagingLevel.get(&pre).unwrap();
        let post_level = StagingLevel.get(&post).unwrap();
        prop_assert_eq!(
            post_level,
            pre_level + expected_delta,
            "{:?}→{:?} expected +{}, got pre={} post={}",
            pre, post, expected_delta, pre_level, post_level
        );
    }

    /// For every pair of Futamura steps, there is either a causal path from
    /// the earlier step to the later one, or they are the same step, or the
    /// later one does not depend on the earlier one. The causal graph is a
    /// well-formed DAG.
    #[test]
    fn prop_futamura_causation_is_well_founded(
        a in arb_futamura_step(),
        b in arb_futamura_step()
    ) {
        let a_effects = causation::effects_of::<FutamuraCausalGraph>(&a);
        let b_effects = causation::effects_of::<FutamuraCausalGraph>(&b);
        // If a causes b, then b does not cause a (no cycles).
        if a_effects.contains(&b) && a != b {
            prop_assert!(!b_effects.contains(&a), "cycle detected: {:?} ⇄ {:?}", a, b);
        }
    }

    /// Every program-like concept (Interpreter, Compiler, Specializer,
    /// CompilerGenerator, and the three program artifacts) descends from
    /// Program in the taxonomy.
    #[test]
    fn prop_program_like_concepts_are_programs(c in arb_stage_concept()) {
        use StageConcept::*;
        let program_like = matches!(
            c,
            Interpreter | Compiler | Specializer | CompilerGenerator
            | SourceProgram | ObjectProgram | ResidualProgram
        );
        if program_like {
            let ancestors = taxonomy::ancestors::<StagingTaxonomy>(&c);
            prop_assert!(
                ancestors.contains(&Program),
                "{:?} is program-like but not classified under Program", c
            );
        }
    }
}
