use crate::ontology::upper::being::Being;

/// Metadata about an ontology — for tracing and introspection.
///
/// Generated automatically by `define_ontology!`. The engine uses this
/// to identify which ontologies participated in a computation.
#[derive(Debug, Clone, Copy)]
pub struct OntologyMeta {
    /// The ontology name (e.g., "BiologyOntology").
    pub name: &'static str,
    /// The module path (e.g., "pr4xis_domains::natural::biomedical::biology").
    pub module_path: &'static str,
}

// =============================================================================
// Annotation types — grounded in OWL/SKOS/DC annotation properties.
//
// These are not strings. Each type corresponds to a concept in the
// OWL annotation ontology (social/software/markup/xml/owl/).
//
// When Ontolex-Lemon is built, Label and Description become references
// to LexicalEntry instances in a Lexicon. The API surface doesn't change.
// =============================================================================

/// A language-tagged string — the minimal Ontolex-compatible annotation.
///
/// Corresponds to an RDF literal with xml:lang. This is the bridge type:
/// currently holds a string + tag, evolves into a LexicalEntry reference
/// when the Lemon lexicon ontology is wired.
#[derive(Debug, Clone)]
pub struct Annotation {
    pub value: &'static str,
    pub lang: &'static str,
}

impl Annotation {
    pub const fn new(value: &'static str) -> Self {
        Self { value, lang: "en" }
    }

    pub const fn with_lang(value: &'static str, lang: &'static str) -> Self {
        Self { value, lang }
    }
}

/// rdfs:label — the preferred human-readable name (skos:prefLabel).
///
/// Instance of OwlConcept::AnnotationProperty.
/// Connected to Lexicon via Ontolex ontolex:canonicalForm.
#[derive(Debug, Clone)]
pub struct Label(pub Annotation);

/// rdfs:comment — a human-readable description (skos:definition).
///
/// Instance of OwlConcept::AnnotationProperty.
#[derive(Debug, Clone)]
pub struct Description(pub Annotation);

/// dc:source — primary citation for the ontology.
///
/// Instance of KnowledgeConcept::DataSource.
/// Connected to Provenance via prov:wasDerivedFrom.
#[derive(Debug, Clone)]
pub struct Citation(pub Annotation);

// =============================================================================
// VocabularyDescriptor — instance of KnowledgeConcept::Vocabulary.
//
// This IS the ontology's self-description. Not a struct with primitives —
// an instance of the Knowledge ontology typed by OWL annotations.
//
// Structural properties (concept_count, morphism_count) are VoID
// statistics: void:classes, void:properties. They are computed from
// Entity::variants().len() / Category::morphisms().len() — causally
// connected to the actual ontology, not stored metadata.
// =============================================================================

/// Runtime descriptor of an ontology — an instance of Knowledge::Vocabulary.
///
/// Generated by `define_ontology!`. Every field is typed by an ontology
/// concept, not by primitives. The eigenform: computed from the actual
/// Category and Entity impls (Smith 1984 causal connection).
#[derive(Debug, Clone)]
pub struct OntologyDescriptor {
    /// rdfs:label — human-readable name (skos:prefLabel).
    pub label: Label,
    /// rdfs:comment — description of what this ontology models.
    pub description: Description,
    /// dc:source — primary academic citation.
    pub source: Citation,
    /// DOLCE classification — what type of being this ontology models.
    pub being: Option<Being>,
    /// Rust module path — implementation-level identity (not ontological).
    pub module_path: &'static str,
    /// void:classes — number of concepts (computed from Entity::variants).
    pub concept_count: usize,
    /// void:properties — number of morphisms (computed from Category::morphisms).
    pub morphism_count: usize,
}

impl OntologyDescriptor {
    /// Domain path derived from module_path.
    pub fn domain(&self) -> String {
        let s = self.module_path;
        let s = s.strip_prefix("pr4xis_domains::").unwrap_or(s);
        let s = s.strip_suffix("::ontology").unwrap_or(s);
        s.replace("::", ".")
    }

    /// The label text in the default language.
    pub fn name(&self) -> &'static str {
        self.label.0.value
    }

    /// Construct a descriptor for ontologies that don't use `define_ontology!`.
    pub fn manual<C: crate::category::Category, E: crate::category::entity::Entity>(
        name: &'static str,
        module_path: &'static str,
        source: &'static str,
        being: Option<Being>,
    ) -> Self {
        Self {
            label: Label(Annotation::new(name)),
            description: Description(Annotation::new("")),
            source: Citation(Annotation::new(source)),
            being,
            module_path,
            concept_count: E::variants().len(),
            morphism_count: C::morphisms().len(),
        }
    }
}
