use crate::ontology::upper::being::Being;

/// Metadata about an ontology — for tracing and introspection.
#[derive(Debug, Clone, Copy)]
pub struct OntologyMeta {
    pub name: &'static str,
    pub module_path: &'static str,
}

/// A Vocabulary — instance of KnowledgeConcept::Vocabulary (VoID).
///
/// An ontology describing itself. Generated by `define_ontology!`.
/// The fields ARE morphisms in the Knowledge category:
///   module_path = identity
///   source = Vocabulary →(DerivedFrom)→ DataSource
///   being = classification morphism to DOLCE
///   concept_count = Vocabulary →(DescribedBy)→ Descriptor (void:classes)
///   morphism_count = Vocabulary →(DescribedBy)→ Descriptor (void:properties)
///
/// Labels and descriptions live in the Lemon lexicon, not here.
/// Transport uses Schema Presentation, not serde.
///
/// Source: W3C VoID (2011); Spivak (2012)
#[derive(Debug, Clone)]
pub struct Vocabulary {
    /// Ontology type name (e.g., "SelfModelOntology").
    pub ontology_name: &'static str,
    pub module_path: &'static str,
    pub source: &'static str,
    pub being: Option<Being>,
    pub concept_count: usize,
    pub morphism_count: usize,
}

impl Vocabulary {
    pub fn domain(&self) -> String {
        let s = self.module_path;
        let s = s.strip_prefix("pr4xis_domains::").unwrap_or(s);
        let s = s.strip_suffix("::ontology").unwrap_or(s);
        s.replace("::", ".")
    }

    pub fn name(&self) -> &'static str {
        self.ontology_name
    }

    pub fn from_ontology<C: crate::category::Category, E: crate::category::entity::Entity>(
        name: &'static str,
        module_path: &'static str,
        source: &'static str,
        being: Option<Being>,
    ) -> Self {
        Self {
            ontology_name: name,
            module_path,
            source,
            being,
            concept_count: E::variants().len(),
            morphism_count: C::morphisms().len(),
        }
    }
}
